// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockFraudHandler is a mock of FraudHandler interface.
type MockFraudHandler struct {
	ctrl     *gomock.Controller
	recorder *MockFraudHandlerMockRecorder
	isgomock struct{}
}

// MockFraudHandlerMockRecorder is the mock recorder for MockFraudHandler.
type MockFraudHandlerMockRecorder struct {
	mock *MockFraudHandler
}

// NewMockFraudHandler creates a new mock instance.
func NewMockFraudHandler(ctrl *gomock.Controller) *MockFraudHandler {
	mock := &MockFraudHandler{ctrl: ctrl}
	mock.recorder = &MockFraudHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFraudHandler) EXPECT() *MockFraudHandlerMockRecorder {
	return m.recorder
}

// BanUser mocks base method.
func (m *MockFraudHandler) BanUser(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BanUser", c)
}

// BanUser indicates an expected call of BanUser.
func (mr *MockFraudHandlerMockRecorder) BanUser(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BanUser", reflect.TypeOf((*MockFraudHandler)(nil).BanUser), c)
}

// GetFraudDashboard mocks base method.
func (m *MockFraudHandler) GetFraudDashboard(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetFraudDashboard", c)
}

// GetFraudDashboard indicates an expected call of GetFraudDashboard.
func (mr *MockFraudHandlerMockRecorder) GetFraudDashboard(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFraudDashboard", reflect.TypeOf((*MockFraudHandler)(nil).GetFraudDashboard), c)
}

// GetFraudTrends mocks base method.
func (m *MockFraudHandler) GetFraudTrends(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetFraudTrends", c)
}

// GetFraudTrends indicates an expected call of GetFraudTrends.
func (mr *MockFraudHandlerMockRecorder) GetFraudTrends(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFraudTrends", reflect.TypeOf((*MockFraudHandler)(nil).GetFraudTrends), c)
}

// GetUserBadgeStatus mocks base method.
func (m *MockFraudHandler) GetUserBadgeStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserBadgeStatus", c)
}

// GetUserBadgeStatus indicates an expected call of GetUserBadgeStatus.
func (mr *MockFraudHandlerMockRecorder) GetUserBadgeStatus(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBadgeStatus", reflect.TypeOf((*MockFraudHandler)(nil).GetUserBadgeStatus), c)
}

// GetUserBotNotifications mocks base method.
func (m *MockFraudHandler) GetUserBotNotifications(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserBotNotifications", c)
}

// GetUserBotNotifications indicates an expected call of GetUserBotNotifications.
func (mr *MockFraudHandlerMockRecorder) GetUserBotNotifications(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserBotNotifications", reflect.TypeOf((*MockFraudHandler)(nil).GetUserBotNotifications), c)
}

// GetUserRiskScore mocks base method.
func (m *MockFraudHandler) GetUserRiskScore(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserRiskScore", c)
}

// GetUserRiskScore indicates an expected call of GetUserRiskScore.
func (mr *MockFraudHandlerMockRecorder) GetUserRiskScore(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRiskScore", reflect.TypeOf((*MockFraudHandler)(nil).GetUserRiskScore), c)
}

// MarkNotificationAsRead mocks base method.
func (m *MockFraudHandler) MarkNotificationAsRead(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkNotificationAsRead", c)
}

// MarkNotificationAsRead indicates an expected call of MarkNotificationAsRead.
func (mr *MockFraudHandlerMockRecorder) MarkNotificationAsRead(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkNotificationAsRead", reflect.TypeOf((*MockFraudHandler)(nil).MarkNotificationAsRead), c)
}

// ReviewUser mocks base method.
func (m *MockFraudHandler) ReviewUser(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ReviewUser", c)
}

// ReviewUser indicates an expected call of ReviewUser.
func (mr *MockFraudHandlerMockRecorder) ReviewUser(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReviewUser", reflect.TypeOf((*MockFraudHandler)(nil).ReviewUser), c)
}

// TriggerBatchAnalysis mocks base method.
func (m *MockFraudHandler) TriggerBatchAnalysis(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "TriggerBatchAnalysis", c)
}

// TriggerBatchAnalysis indicates an expected call of TriggerBatchAnalysis.
func (mr *MockFraudHandlerMockRecorder) TriggerBatchAnalysis(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TriggerBatchAnalysis", reflect.TypeOf((*MockFraudHandler)(nil).TriggerBatchAnalysis), c)
}
