// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleHandler is a mock of RoleHandler interface.
type MockRoleHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRoleHandlerMockRecorder
	isgomock struct{}
}

// MockRoleHandlerMockRecorder is the mock recorder for MockRoleHandler.
type MockRoleHandlerMockRecorder struct {
	mock *MockRoleHandler
}

// NewMockRoleHandler creates a new mock instance.
func NewMockRoleHandler(ctrl *gomock.Controller) *MockRoleHandler {
	mock := &MockRoleHandler{ctrl: ctrl}
	mock.recorder = &MockRoleHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleHandler) EXPECT() *MockRoleHandlerMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockRoleHandler) AssignRole(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignRole", c)
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleHandlerMockRecorder) AssignRole(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleHandler)(nil).AssignRole), c)
}

// Create mocks base method.
func (m *MockRoleHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockRoleHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRoleHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockRoleHandler) Delete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete.
func (mr *MockRoleHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRoleHandler)(nil).Delete), c)
}

// GetByID mocks base method.
func (m *MockRoleHandler) GetByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByID", c)
}

// GetByID indicates an expected call of GetByID.
func (mr *MockRoleHandlerMockRecorder) GetByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockRoleHandler)(nil).GetByID), c)
}

// GetMyPermission mocks base method.
func (m *MockRoleHandler) GetMyPermission(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetMyPermission", c)
}

// GetMyPermission indicates an expected call of GetMyPermission.
func (mr *MockRoleHandlerMockRecorder) GetMyPermission(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyPermission", reflect.TypeOf((*MockRoleHandler)(nil).GetMyPermission), c)
}

// GetUserRoles mocks base method.
func (m *MockRoleHandler) GetUserRoles(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserRoles", c)
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockRoleHandlerMockRecorder) GetUserRoles(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockRoleHandler)(nil).GetUserRoles), c)
}

// List mocks base method.
func (m *MockRoleHandler) List(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", c)
}

// List indicates an expected call of List.
func (mr *MockRoleHandlerMockRecorder) List(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRoleHandler)(nil).List), c)
}

// RemoveRole mocks base method.
func (m *MockRoleHandler) RemoveRole(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveRole", c)
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRoleHandlerMockRecorder) RemoveRole(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRoleHandler)(nil).RemoveRole), c)
}

// SetPermission mocks base method.
func (m *MockRoleHandler) SetPermission(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetPermission", c)
}

// SetPermission indicates an expected call of SetPermission.
func (mr *MockRoleHandlerMockRecorder) SetPermission(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermission", reflect.TypeOf((*MockRoleHandler)(nil).SetPermission), c)
}

// Update mocks base method.
func (m *MockRoleHandler) Update(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update.
func (mr *MockRoleHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRoleHandler)(nil).Update), c)
}
