// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTagUseCase is a mock of TagUseCase interface.
type MockTagUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockTagUseCaseMockRecorder
	isgomock struct{}
}

// MockTagUseCaseMockRecorder is the mock recorder for MockTagUseCase.
type MockTagUseCaseMockRecorder struct {
	mock *MockTagUseCase
}

// NewMockTagUseCase creates a new mock instance.
func NewMockTagUseCase(ctrl *gomock.Controller) *MockTagUseCase {
	mock := &MockTagUseCase{ctrl: ctrl}
	mock.recorder = &MockTagUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagUseCase) EXPECT() *MockTagUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockTagUseCase) Create(ctx context.Context, req *dto.CreateTagRequest) (*dto.TagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.TagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockTagUseCaseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagUseCase)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockTagUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockTagUseCase) GetByID(ctx context.Context, id uuid.UUID) (*dto.TagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.TagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockTagUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockTagUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockTagUseCase) List(ctx context.Context, page, pageSize int) (*repository.PaginatedResult[dto.TagResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.TagResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockTagUseCaseMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockTagUseCase)(nil).List), ctx, page, pageSize)
}

// Update mocks base method.
func (m *MockTagUseCase) Update(ctx context.Context, id uuid.UUID, req *dto.UpdateTagRequest) (*dto.TagResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.TagResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockTagUseCaseMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagUseCase)(nil).Update), ctx, id, req)
}
