// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesHandler is a mock of SeriesHandler interface.
type MockSeriesHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesHandlerMockRecorder
	isgomock struct{}
}

// MockSeriesHandlerMockRecorder is the mock recorder for MockSeriesHandler.
type MockSeriesHandlerMockRecorder struct {
	mock *MockSeriesHandler
}

// NewMockSeriesHandler creates a new mock instance.
func NewMockSeriesHandler(ctrl *gomock.Controller) *MockSeriesHandler {
	mock := &MockSeriesHandler{ctrl: ctrl}
	mock.recorder = &MockSeriesHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesHandler) EXPECT() *MockSeriesHandlerMockRecorder {
	return m.recorder
}

// AddBlog mocks base method.
func (m *MockSeriesHandler) AddBlog(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddBlog", c)
}

// AddBlog indicates an expected call of AddBlog.
func (mr *MockSeriesHandlerMockRecorder) AddBlog(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlog", reflect.TypeOf((*MockSeriesHandler)(nil).AddBlog), c)
}

// Create mocks base method.
func (m *MockSeriesHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockSeriesHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSeriesHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockSeriesHandler) Delete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete.
func (mr *MockSeriesHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSeriesHandler)(nil).Delete), c)
}

// GetByID mocks base method.
func (m *MockSeriesHandler) GetByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByID", c)
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSeriesHandlerMockRecorder) GetByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSeriesHandler)(nil).GetByID), c)
}

// GetBySlug mocks base method.
func (m *MockSeriesHandler) GetBySlug(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetBySlug", c)
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockSeriesHandlerMockRecorder) GetBySlug(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockSeriesHandler)(nil).GetBySlug), c)
}

// List mocks base method.
func (m *MockSeriesHandler) List(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", c)
}

// List indicates an expected call of List.
func (mr *MockSeriesHandlerMockRecorder) List(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSeriesHandler)(nil).List), c)
}

// RemoveBlog mocks base method.
func (m *MockSeriesHandler) RemoveBlog(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RemoveBlog", c)
}

// RemoveBlog indicates an expected call of RemoveBlog.
func (mr *MockSeriesHandlerMockRecorder) RemoveBlog(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBlog", reflect.TypeOf((*MockSeriesHandler)(nil).RemoveBlog), c)
}

// Update mocks base method.
func (m *MockSeriesHandler) Update(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update.
func (mr *MockSeriesHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeriesHandler)(nil).Update), c)
}
