// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	multipart "mime/multipart"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileUseCase is a mock of ProfileUseCase interface.
type MockProfileUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProfileUseCaseMockRecorder
	isgomock struct{}
}

// MockProfileUseCaseMockRecorder is the mock recorder for MockProfileUseCase.
type MockProfileUseCaseMockRecorder struct {
	mock *MockProfileUseCase
}

// NewMockProfileUseCase creates a new mock instance.
func NewMockProfileUseCase(ctrl *gomock.Controller) *MockProfileUseCase {
	mock := &MockProfileUseCase{ctrl: ctrl}
	mock.recorder = &MockProfileUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileUseCase) EXPECT() *MockProfileUseCaseMockRecorder {
	return m.recorder
}

// GetProfile mocks base method.
func (m *MockProfileUseCase) GetProfile(ctx context.Context, userID uuid.UUID) (*dto.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, userID)
	ret0, _ := ret[0].(*dto.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockProfileUseCaseMockRecorder) GetProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockProfileUseCase)(nil).GetProfile), ctx, userID)
}

// GetPublicProfile mocks base method.
func (m *MockProfileUseCase) GetPublicProfile(ctx context.Context, userID uuid.UUID) (*dto.PublicProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicProfile", ctx, userID)
	ret0, _ := ret[0].(*dto.PublicProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPublicProfile indicates an expected call of GetPublicProfile.
func (mr *MockProfileUseCaseMockRecorder) GetPublicProfile(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfile", reflect.TypeOf((*MockProfileUseCase)(nil).GetPublicProfile), ctx, userID)
}

// UpdateProfile mocks base method.
func (m *MockProfileUseCase) UpdateProfile(ctx context.Context, userID uuid.UUID, req dto.UpdateProfileRequest) (*dto.ProfileResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateProfile", ctx, userID, req)
	ret0, _ := ret[0].(*dto.ProfileResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateProfile indicates an expected call of UpdateProfile.
func (mr *MockProfileUseCaseMockRecorder) UpdateProfile(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateProfile", reflect.TypeOf((*MockProfileUseCase)(nil).UpdateProfile), ctx, userID, req)
}

// UploadAvatar mocks base method.
func (m *MockProfileUseCase) UploadAvatar(ctx context.Context, userID uuid.UUID, file *multipart.FileHeader) (*dto.AvatarUploadResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadAvatar", ctx, userID, file)
	ret0, _ := ret[0].(*dto.AvatarUploadResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockProfileUseCaseMockRecorder) UploadAvatar(ctx, userID, file any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockProfileUseCase)(nil).UploadAvatar), ctx, userID, file)
}
