// Code generated by MockGen. DO NOT EDIT.
// Source: internal/interfaces/http/handler/payment/handler.go
// Source: internal/application/usecase/payment/process_webhook.go
//
// Generated by this command:
//
//	mockgen -source=internal/interfaces/http/handler/payment/handler.go -destination=internal/interfaces/http/handler/payment/mocks/mock_handler.go -package=mocks
//	mockgen -source=internal/application/usecase/payment/process_webhook.go -destination=internal/interfaces/http/handler/payment/mocks/mock_process_webhook.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	entity "github.com/aiagent/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockCreatePaymentUseCase is a mock of CreatePaymentUseCase interface.
type MockCreatePaymentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCreatePaymentUseCaseRecorder
}

// MockCreatePaymentUseCaseRecorder is the mock recorder for MockCreatePaymentUseCase.
type MockCreatePaymentUseCaseRecorder struct {
	mock *MockCreatePaymentUseCase
}

// NewMockCreatePaymentUseCase creates a new mock instance.
func NewMockCreatePaymentUseCase(ctrl *gomock.Controller) *MockCreatePaymentUseCase {
	mock := &MockCreatePaymentUseCase{ctrl: ctrl}
	mock.recorder = &MockCreatePaymentUseCaseRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCreatePaymentUseCase) EXPECT() *MockCreatePaymentUseCaseRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockCreatePaymentUseCase) Execute(ctx context.Context, req dto.CreatePaymentRequest) (*dto.CreatePaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*dto.CreatePaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockCreatePaymentUseCaseRecorder) Execute(ctx, req any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockCreatePaymentUseCase)(nil).Execute), ctx, req)
}

// MockProcessWebhookUseCase is a mock of ProcessWebhookUseCase interface.
type MockProcessWebhookUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProcessWebhookUseCaseRecorder
}

// MockProcessWebhookUseCaseRecorder is the mock recorder for MockProcessWebhookUseCase.
type MockProcessWebhookUseCaseRecorder struct {
	mock *MockProcessWebhookUseCase
}

// NewMockProcessWebhookUseCase creates a new mock instance.
func NewMockProcessWebhookUseCase(ctrl *gomock.Controller) *MockProcessWebhookUseCase {
	mock := &MockProcessWebhookUseCase{ctrl: ctrl}
	mock.recorder = &MockProcessWebhookUseCaseRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessWebhookUseCase) EXPECT() *MockProcessWebhookUseCaseRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProcessWebhookUseCase) Execute(ctx context.Context, req dto.ProcessWebhookRequest) (*entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProcessWebhookUseCaseRecorder) Execute(ctx, req any) *gomock.Call {
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProcessWebhookUseCase)(nil).Execute), ctx, req)
}
