// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockBookmarkHandler is a mock of BookmarkHandler interface.
type MockBookmarkHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBookmarkHandlerMockRecorder
	isgomock struct{}
}

// MockBookmarkHandlerMockRecorder is the mock recorder for MockBookmarkHandler.
type MockBookmarkHandlerMockRecorder struct {
	mock *MockBookmarkHandler
}

// NewMockBookmarkHandler creates a new mock instance.
func NewMockBookmarkHandler(ctrl *gomock.Controller) *MockBookmarkHandler {
	mock := &MockBookmarkHandler{ctrl: ctrl}
	mock.recorder = &MockBookmarkHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookmarkHandler) EXPECT() *MockBookmarkHandlerMockRecorder {
	return m.recorder
}

// Bookmark mocks base method.
func (m *MockBookmarkHandler) Bookmark(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Bookmark", c)
}

// Bookmark indicates an expected call of Bookmark.
func (mr *MockBookmarkHandlerMockRecorder) Bookmark(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bookmark", reflect.TypeOf((*MockBookmarkHandler)(nil).Bookmark), c)
}

// List mocks base method.
func (m *MockBookmarkHandler) List(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", c)
}

// List indicates an expected call of List.
func (mr *MockBookmarkHandlerMockRecorder) List(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBookmarkHandler)(nil).List), c)
}

// Unbookmark mocks base method.
func (m *MockBookmarkHandler) Unbookmark(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unbookmark", c)
}

// Unbookmark indicates an expected call of Unbookmark.
func (mr *MockBookmarkHandlerMockRecorder) Unbookmark(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unbookmark", reflect.TypeOf((*MockBookmarkHandler)(nil).Unbookmark), c)
}
