// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockProfileHandler is a mock of ProfileHandler interface.
type MockProfileHandler struct {
	ctrl     *gomock.Controller
	recorder *MockProfileHandlerMockRecorder
	isgomock struct{}
}

// MockProfileHandlerMockRecorder is the mock recorder for MockProfileHandler.
type MockProfileHandlerMockRecorder struct {
	mock *MockProfileHandler
}

// NewMockProfileHandler creates a new mock instance.
func NewMockProfileHandler(ctrl *gomock.Controller) *MockProfileHandler {
	mock := &MockProfileHandler{ctrl: ctrl}
	mock.recorder = &MockProfileHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProfileHandler) EXPECT() *MockProfileHandlerMockRecorder {
	return m.recorder
}

// GetMyProfile mocks base method.
func (m *MockProfileHandler) GetMyProfile(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetMyProfile", c)
}

// GetMyProfile indicates an expected call of GetMyProfile.
func (mr *MockProfileHandlerMockRecorder) GetMyProfile(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMyProfile", reflect.TypeOf((*MockProfileHandler)(nil).GetMyProfile), c)
}

// GetPublicProfile mocks base method.
func (m *MockProfileHandler) GetPublicProfile(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPublicProfile", c)
}

// GetPublicProfile indicates an expected call of GetPublicProfile.
func (mr *MockProfileHandlerMockRecorder) GetPublicProfile(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicProfile", reflect.TypeOf((*MockProfileHandler)(nil).GetPublicProfile), c)
}

// UpdateMyProfile mocks base method.
func (m *MockProfileHandler) UpdateMyProfile(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateMyProfile", c)
}

// UpdateMyProfile indicates an expected call of UpdateMyProfile.
func (mr *MockProfileHandlerMockRecorder) UpdateMyProfile(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMyProfile", reflect.TypeOf((*MockProfileHandler)(nil).UpdateMyProfile), c)
}

// UploadAvatar mocks base method.
func (m *MockProfileHandler) UploadAvatar(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UploadAvatar", c)
}

// UploadAvatar indicates an expected call of UploadAvatar.
func (mr *MockProfileHandlerMockRecorder) UploadAvatar(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadAvatar", reflect.TypeOf((*MockProfileHandler)(nil).UploadAvatar), c)
}
