// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockBlogHandler is a mock of BlogHandler interface.
type MockBlogHandler struct {
	ctrl     *gomock.Controller
	recorder *MockBlogHandlerMockRecorder
	isgomock struct{}
}

// MockBlogHandlerMockRecorder is the mock recorder for MockBlogHandler.
type MockBlogHandlerMockRecorder struct {
	mock *MockBlogHandler
}

// NewMockBlogHandler creates a new mock instance.
func NewMockBlogHandler(ctrl *gomock.Controller) *MockBlogHandler {
	mock := &MockBlogHandler{ctrl: ctrl}
	mock.recorder = &MockBlogHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogHandler) EXPECT() *MockBlogHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlogHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockBlogHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlogHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockBlogHandler) Delete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogHandler)(nil).Delete), c)
}

// GetByID mocks base method.
func (m *MockBlogHandler) GetByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByID", c)
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBlogHandlerMockRecorder) GetByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBlogHandler)(nil).GetByID), c)
}

// List mocks base method.
func (m *MockBlogHandler) List(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", c)
}

// List indicates an expected call of List.
func (mr *MockBlogHandlerMockRecorder) List(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlogHandler)(nil).List), c)
}

// Publish mocks base method.
func (m *MockBlogHandler) Publish(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Publish", c)
}

// Publish indicates an expected call of Publish.
func (mr *MockBlogHandlerMockRecorder) Publish(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBlogHandler)(nil).Publish), c)
}

// React mocks base method.
func (m *MockBlogHandler) React(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "React", c)
}

// React indicates an expected call of React.
func (mr *MockBlogHandlerMockRecorder) React(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "React", reflect.TypeOf((*MockBlogHandler)(nil).React), c)
}

// Unpublish mocks base method.
func (m *MockBlogHandler) Unpublish(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unpublish", c)
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockBlogHandlerMockRecorder) Unpublish(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockBlogHandler)(nil).Unpublish), c)
}

// Update mocks base method.
func (m *MockBlogHandler) Update(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update.
func (mr *MockBlogHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlogHandler)(nil).Update), c)
}
