// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthHandler is a mock of HealthHandler interface.
type MockHealthHandler struct {
	ctrl     *gomock.Controller
	recorder *MockHealthHandlerMockRecorder
	isgomock struct{}
}

// MockHealthHandlerMockRecorder is the mock recorder for MockHealthHandler.
type MockHealthHandlerMockRecorder struct {
	mock *MockHealthHandler
}

// NewMockHealthHandler creates a new mock instance.
func NewMockHealthHandler(ctrl *gomock.Controller) *MockHealthHandler {
	mock := &MockHealthHandler{ctrl: ctrl}
	mock.recorder = &MockHealthHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthHandler) EXPECT() *MockHealthHandlerMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthHandler) Check(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Check", c)
}

// Check indicates an expected call of Check.
func (mr *MockHealthHandlerMockRecorder) Check(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthHandler)(nil).Check), c)
}

// Ping mocks base method.
func (m *MockHealthHandler) Ping(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Ping", c)
}

// Ping indicates an expected call of Ping.
func (mr *MockHealthHandlerMockRecorder) Ping(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ping", reflect.TypeOf((*MockHealthHandler)(nil).Ping), c)
}
