// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentHandler is a mock of CommentHandler interface.
type MockCommentHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCommentHandlerMockRecorder
	isgomock struct{}
}

// MockCommentHandlerMockRecorder is the mock recorder for MockCommentHandler.
type MockCommentHandlerMockRecorder struct {
	mock *MockCommentHandler
}

// NewMockCommentHandler creates a new mock instance.
func NewMockCommentHandler(ctrl *gomock.Controller) *MockCommentHandler {
	mock := &MockCommentHandler{ctrl: ctrl}
	mock.recorder = &MockCommentHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentHandler) EXPECT() *MockCommentHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockCommentHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockCommentHandler) Delete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentHandler)(nil).Delete), c)
}

// GetByBlogID mocks base method.
func (m *MockCommentHandler) GetByBlogID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByBlogID", c)
}

// GetByBlogID indicates an expected call of GetByBlogID.
func (mr *MockCommentHandlerMockRecorder) GetByBlogID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBlogID", reflect.TypeOf((*MockCommentHandler)(nil).GetByBlogID), c)
}

// Update mocks base method.
func (m *MockCommentHandler) Update(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update.
func (mr *MockCommentHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentHandler)(nil).Update), c)
}
