// Code generated by MockGen. DO NOT EDIT.
// Source: reading_history_handler.go
//
// Generated by this command:
//
//	mockgen -source=reading_history_handler.go -destination=mocks/mock_reading_history_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockReadingHistoryHandler is a mock of ReadingHistoryHandler interface.
type MockReadingHistoryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockReadingHistoryHandlerMockRecorder
	isgomock struct{}
}

// MockReadingHistoryHandlerMockRecorder is the mock recorder for MockReadingHistoryHandler.
type MockReadingHistoryHandlerMockRecorder struct {
	mock *MockReadingHistoryHandler
}

// NewMockReadingHistoryHandler creates a new mock instance.
func NewMockReadingHistoryHandler(ctrl *gomock.Controller) *MockReadingHistoryHandler {
	mock := &MockReadingHistoryHandler{ctrl: ctrl}
	mock.recorder = &MockReadingHistoryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingHistoryHandler) EXPECT() *MockReadingHistoryHandlerMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockReadingHistoryHandler) GetHistory(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetHistory", c)
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockReadingHistoryHandlerMockRecorder) GetHistory(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockReadingHistoryHandler)(nil).GetHistory), c)
}

// MarkAsRead mocks base method.
func (m *MockReadingHistoryHandler) MarkAsRead(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "MarkAsRead", c)
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockReadingHistoryHandlerMockRecorder) MarkAsRead(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockReadingHistoryHandler)(nil).MarkAsRead), c)
}
