// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionUseCase is a mock of SubscriptionUseCase interface.
type MockSubscriptionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionUseCaseMockRecorder
	isgomock struct{}
}

// MockSubscriptionUseCaseMockRecorder is the mock recorder for MockSubscriptionUseCase.
type MockSubscriptionUseCaseMockRecorder struct {
	mock *MockSubscriptionUseCase
}

// NewMockSubscriptionUseCase creates a new mock instance.
func NewMockSubscriptionUseCase(ctrl *gomock.Controller) *MockSubscriptionUseCase {
	mock := &MockSubscriptionUseCase{ctrl: ctrl}
	mock.recorder = &MockSubscriptionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionUseCase) EXPECT() *MockSubscriptionUseCaseMockRecorder {
	return m.recorder
}

// CountSubscribers mocks base method.
func (m *MockSubscriptionUseCase) CountSubscribers(ctx context.Context, authorID uuid.UUID) (*dto.SubscriptionCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscribers", ctx, authorID)
	ret0, _ := ret[0].(*dto.SubscriptionCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscribers indicates an expected call of CountSubscribers.
func (mr *MockSubscriptionUseCaseMockRecorder) CountSubscribers(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscribers", reflect.TypeOf((*MockSubscriptionUseCase)(nil).CountSubscribers), ctx, authorID)
}

// GetSubscribers mocks base method.
func (m *MockSubscriptionUseCase) GetSubscribers(ctx context.Context, authorID uuid.UUID, page, pageSize int) (*repository.PaginatedResult[dto.SubscriptionResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscribers", ctx, authorID, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.SubscriptionResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockSubscriptionUseCaseMockRecorder) GetSubscribers(ctx, authorID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockSubscriptionUseCase)(nil).GetSubscribers), ctx, authorID, page, pageSize)
}

// GetSubscriptionCounts mocks base method.
func (m *MockSubscriptionUseCase) GetSubscriptionCounts(ctx context.Context, userID uuid.UUID) (*dto.SubscriptionCountResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptionCounts", ctx, userID)
	ret0, _ := ret[0].(*dto.SubscriptionCountResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptionCounts indicates an expected call of GetSubscriptionCounts.
func (mr *MockSubscriptionUseCaseMockRecorder) GetSubscriptionCounts(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionCounts", reflect.TypeOf((*MockSubscriptionUseCase)(nil).GetSubscriptionCounts), ctx, userID)
}

// GetSubscriptions mocks base method.
func (m *MockSubscriptionUseCase) GetSubscriptions(ctx context.Context, subscriberID uuid.UUID, page, pageSize int) (*repository.PaginatedResult[dto.SubscriptionResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSubscriptions", ctx, subscriberID, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.SubscriptionResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSubscriptions indicates an expected call of GetSubscriptions.
func (mr *MockSubscriptionUseCaseMockRecorder) GetSubscriptions(ctx, subscriberID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptions", reflect.TypeOf((*MockSubscriptionUseCase)(nil).GetSubscriptions), ctx, subscriberID, page, pageSize)
}

// IsSubscribed mocks base method.
func (m *MockSubscriptionUseCase) IsSubscribed(ctx context.Context, subscriberID, authorID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsSubscribed", ctx, subscriberID, authorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsSubscribed indicates an expected call of IsSubscribed.
func (mr *MockSubscriptionUseCaseMockRecorder) IsSubscribed(ctx, subscriberID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsSubscribed", reflect.TypeOf((*MockSubscriptionUseCase)(nil).IsSubscribed), ctx, subscriberID, authorID)
}

// Subscribe mocks base method.
func (m *MockSubscriptionUseCase) Subscribe(ctx context.Context, subscriberID, authorID uuid.UUID) (*dto.SubscriptionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, subscriberID, authorID)
	ret0, _ := ret[0].(*dto.SubscriptionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubscriptionUseCaseMockRecorder) Subscribe(ctx, subscriberID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubscriptionUseCase)(nil).Subscribe), ctx, subscriberID, authorID)
}

// Unsubscribe mocks base method.
func (m *MockSubscriptionUseCase) Unsubscribe(ctx context.Context, subscriberID, authorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unsubscribe", ctx, subscriberID, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriptionUseCaseMockRecorder) Unsubscribe(ctx, subscriberID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriptionUseCase)(nil).Unsubscribe), ctx, subscriberID, authorID)
}
