// Code generated by MockGen. DO NOT EDIT.
// Source: health_usecase.go
//
// Generated by this command:
//
//	mockgen -source=health_usecase.go -destination=mocks/mock_health_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	gomock "go.uber.org/mock/gomock"
)

// MockHealthUseCase is a mock of HealthUseCase interface.
type MockHealthUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockHealthUseCaseMockRecorder
	isgomock struct{}
}

// MockHealthUseCaseMockRecorder is the mock recorder for MockHealthUseCase.
type MockHealthUseCaseMockRecorder struct {
	mock *MockHealthUseCase
}

// NewMockHealthUseCase creates a new mock instance.
func NewMockHealthUseCase(ctrl *gomock.Controller) *MockHealthUseCase {
	mock := &MockHealthUseCase{ctrl: ctrl}
	mock.recorder = &MockHealthUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHealthUseCase) EXPECT() *MockHealthUseCaseMockRecorder {
	return m.recorder
}

// Check mocks base method.
func (m *MockHealthUseCase) Check(ctx context.Context) *dto.HealthResponse {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Check", ctx)
	ret0, _ := ret[0].(*dto.HealthResponse)
	return ret0
}

// Check indicates an expected call of Check.
func (mr *MockHealthUseCaseMockRecorder) Check(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Check", reflect.TypeOf((*MockHealthUseCase)(nil).Check), ctx)
}
