// Code generated by MockGen. DO NOT EDIT.
// Source: ranking_usecase.go
//
// Generated by this command:
//
//	mockgen -source=ranking_usecase.go -destination=mocks/mock_ranking_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRankingUseCase is a mock of RankingUseCase interface.
type MockRankingUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRankingUseCaseMockRecorder
	isgomock struct{}
}

// MockRankingUseCaseMockRecorder is the mock recorder for MockRankingUseCase.
type MockRankingUseCaseMockRecorder struct {
	mock *MockRankingUseCase
}

// NewMockRankingUseCase creates a new mock instance.
func NewMockRankingUseCase(ctrl *gomock.Controller) *MockRankingUseCase {
	mock := &MockRankingUseCase{ctrl: ctrl}
	mock.recorder = &MockRankingUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingUseCase) EXPECT() *MockRankingUseCaseMockRecorder {
	return m.recorder
}

// GetTopUsers mocks base method.
func (m *MockRankingUseCase) GetTopUsers(ctx context.Context, params *dto.RankingFilterParams) (*repository.PaginatedResult[dto.RankedUserResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTopUsers", ctx, params)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.RankedUserResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTopUsers indicates an expected call of GetTopUsers.
func (mr *MockRankingUseCaseMockRecorder) GetTopUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTopUsers", reflect.TypeOf((*MockRankingUseCase)(nil).GetTopUsers), ctx, params)
}

// GetTrendingUsers mocks base method.
func (m *MockRankingUseCase) GetTrendingUsers(ctx context.Context, params *dto.RankingFilterParams) (*repository.PaginatedResult[dto.RankedUserResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrendingUsers", ctx, params)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.RankedUserResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrendingUsers indicates an expected call of GetTrendingUsers.
func (mr *MockRankingUseCaseMockRecorder) GetTrendingUsers(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrendingUsers", reflect.TypeOf((*MockRankingUseCase)(nil).GetTrendingUsers), ctx, params)
}

// GetUserRanking mocks base method.
func (m *MockRankingUseCase) GetUserRanking(ctx context.Context, userID uuid.UUID) (*dto.UserRankingDetailResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRanking", ctx, userID)
	ret0, _ := ret[0].(*dto.UserRankingDetailResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRanking indicates an expected call of GetUserRanking.
func (mr *MockRankingUseCaseMockRecorder) GetUserRanking(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRanking", reflect.TypeOf((*MockRankingUseCase)(nil).GetUserRanking), ctx, userID)
}

// RecalculateAllScores mocks base method.
func (m *MockRankingUseCase) RecalculateAllScores(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecalculateAllScores", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// RecalculateAllScores indicates an expected call of RecalculateAllScores.
func (mr *MockRankingUseCaseMockRecorder) RecalculateAllScores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateAllScores", reflect.TypeOf((*MockRankingUseCase)(nil).RecalculateAllScores), ctx)
}
