// Code generated by MockGen. DO NOT EDIT.
// Source: blog_usecase.go
//
// Generated by this command:
//
//	mockgen -source=blog_usecase.go -destination=mocks/mock_blog_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBlogUseCase is a mock of BlogUseCase interface.
type MockBlogUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockBlogUseCaseMockRecorder
	isgomock struct{}
}

// MockBlogUseCaseMockRecorder is the mock recorder for MockBlogUseCase.
type MockBlogUseCaseMockRecorder struct {
	mock *MockBlogUseCase
}

// NewMockBlogUseCase creates a new mock instance.
func NewMockBlogUseCase(ctrl *gomock.Controller) *MockBlogUseCase {
	mock := &MockBlogUseCase{ctrl: ctrl}
	mock.recorder = &MockBlogUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogUseCase) EXPECT() *MockBlogUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockBlogUseCase) Create(ctx context.Context, authorID uuid.UUID, req *dto.CreateBlogRequest) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, authorID, req)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockBlogUseCaseMockRecorder) Create(ctx, authorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlogUseCase)(nil).Create), ctx, authorID, req)
}

// Delete mocks base method.
func (m *MockBlogUseCase) Delete(ctx context.Context, id, authorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogUseCaseMockRecorder) Delete(ctx, id, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogUseCase)(nil).Delete), ctx, id, authorID)
}

// GetByID mocks base method.
func (m *MockBlogUseCase) GetByID(ctx context.Context, id uuid.UUID, viewerID *uuid.UUID) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, viewerID)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBlogUseCaseMockRecorder) GetByID(ctx, id, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBlogUseCase)(nil).GetByID), ctx, id, viewerID)
}

// GetBySlug mocks base method.
func (m *MockBlogUseCase) GetBySlug(ctx context.Context, authorID uuid.UUID, slug string, viewerID *uuid.UUID) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, authorID, slug, viewerID)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockBlogUseCaseMockRecorder) GetBySlug(ctx, authorID, slug, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockBlogUseCase)(nil).GetBySlug), ctx, authorID, slug, viewerID)
}

// List mocks base method.
func (m *MockBlogUseCase) List(ctx context.Context, params *dto.BlogFilterParams, viewerID *uuid.UUID) (*repository.PaginatedResult[dto.BlogListResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params, viewerID)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.BlogListResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBlogUseCaseMockRecorder) List(ctx, params, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlogUseCase)(nil).List), ctx, params, viewerID)
}

// Publish mocks base method.
func (m *MockBlogUseCase) Publish(ctx context.Context, id, authorID uuid.UUID, req *dto.PublishBlogRequest) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id, authorID, req)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockBlogUseCaseMockRecorder) Publish(ctx, id, authorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBlogUseCase)(nil).Publish), ctx, id, authorID, req)
}

// React mocks base method.
func (m *MockBlogUseCase) React(ctx context.Context, id, userID uuid.UUID, req *dto.ReactionRequest) (*dto.ReactionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "React", ctx, id, userID, req)
	ret0, _ := ret[0].(*dto.ReactionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// React indicates an expected call of React.
func (mr *MockBlogUseCaseMockRecorder) React(ctx, id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "React", reflect.TypeOf((*MockBlogUseCase)(nil).React), ctx, id, userID, req)
}

// Unpublish mocks base method.
func (m *MockBlogUseCase) Unpublish(ctx context.Context, id, authorID uuid.UUID) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", ctx, id, authorID)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockBlogUseCaseMockRecorder) Unpublish(ctx, id, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockBlogUseCase)(nil).Unpublish), ctx, id, authorID)
}

// Update mocks base method.
func (m *MockBlogUseCase) Update(ctx context.Context, id, authorID uuid.UUID, req *dto.UpdateBlogRequest) (*dto.BlogResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, authorID, req)
	ret0, _ := ret[0].(*dto.BlogResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockBlogUseCaseMockRecorder) Update(ctx, id, authorID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlogUseCase)(nil).Update), ctx, id, authorID, req)
}
