// Code generated by MockGen. DO NOT EDIT.
// Source: comment_usecase.go
//
// Generated by this command:
//
//	mockgen -source=comment_usecase.go -destination=mocks/mock_comment_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCommentUseCase is a mock of CommentUseCase interface.
type MockCommentUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCommentUseCaseMockRecorder
	isgomock struct{}
}

// MockCommentUseCaseMockRecorder is the mock recorder for MockCommentUseCase.
type MockCommentUseCaseMockRecorder struct {
	mock *MockCommentUseCase
}

// NewMockCommentUseCase creates a new mock instance.
func NewMockCommentUseCase(ctrl *gomock.Controller) *MockCommentUseCase {
	mock := &MockCommentUseCase{ctrl: ctrl}
	mock.recorder = &MockCommentUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommentUseCase) EXPECT() *MockCommentUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCommentUseCase) Create(ctx context.Context, userID, blogID uuid.UUID, req *dto.CreateCommentRequest) (*dto.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, userID, blogID, req)
	ret0, _ := ret[0].(*dto.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCommentUseCaseMockRecorder) Create(ctx, userID, blogID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCommentUseCase)(nil).Create), ctx, userID, blogID, req)
}

// Delete mocks base method.
func (m *MockCommentUseCase) Delete(ctx context.Context, id, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCommentUseCaseMockRecorder) Delete(ctx, id, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCommentUseCase)(nil).Delete), ctx, id, userID)
}

// GetByBlogID mocks base method.
func (m *MockCommentUseCase) GetByBlogID(ctx context.Context, blogID uuid.UUID, page, pageSize int) (*repository.PaginatedResult[dto.CommentResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByBlogID", ctx, blogID, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.CommentResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByBlogID indicates an expected call of GetByBlogID.
func (mr *MockCommentUseCaseMockRecorder) GetByBlogID(ctx, blogID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByBlogID", reflect.TypeOf((*MockCommentUseCase)(nil).GetByBlogID), ctx, blogID, page, pageSize)
}

// GetByID mocks base method.
func (m *MockCommentUseCase) GetByID(ctx context.Context, id uuid.UUID) (*dto.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCommentUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCommentUseCase)(nil).GetByID), ctx, id)
}

// Update mocks base method.
func (m *MockCommentUseCase) Update(ctx context.Context, id, userID uuid.UUID, req *dto.UpdateCommentRequest) (*dto.CommentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, userID, req)
	ret0, _ := ret[0].(*dto.CommentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCommentUseCaseMockRecorder) Update(ctx, id, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCommentUseCase)(nil).Update), ctx, id, userID, req)
}
