// Code generated by MockGen. DO NOT EDIT.
// Source: permission_usecase.go
//
// Generated by this command:
//
//	mockgen -source=permission_usecase.go -destination=mocks/mock_permission_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionUseCase is a mock of PermissionUseCase interface.
type MockPermissionUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionUseCaseMockRecorder
	isgomock struct{}
}

// MockPermissionUseCaseMockRecorder is the mock recorder for MockPermissionUseCase.
type MockPermissionUseCaseMockRecorder struct {
	mock *MockPermissionUseCase
}

// NewMockPermissionUseCase creates a new mock instance.
func NewMockPermissionUseCase(ctrl *gomock.Controller) *MockPermissionUseCase {
	mock := &MockPermissionUseCase{ctrl: ctrl}
	mock.recorder = &MockPermissionUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionUseCase) EXPECT() *MockPermissionUseCaseMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockPermissionUseCase) CheckPermission(ctx context.Context, userID uuid.UUID, resource, permissionName string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, resource, permissionName)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPermissionUseCaseMockRecorder) CheckPermission(ctx, userID, resource, permissionName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPermissionUseCase)(nil).CheckPermission), ctx, userID, resource, permissionName)
}

// GetUserPermission mocks base method.
func (m *MockPermissionUseCase) GetUserPermission(ctx context.Context, userID uuid.UUID, resource string) (*dto.UserPermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermission", ctx, userID, resource)
	ret0, _ := ret[0].(*dto.UserPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermission indicates an expected call of GetUserPermission.
func (mr *MockPermissionUseCaseMockRecorder) GetUserPermission(ctx, userID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermission", reflect.TypeOf((*MockPermissionUseCase)(nil).GetUserPermission), ctx, userID, resource)
}

// InvalidateResourcePermissions mocks base method.
func (m *MockPermissionUseCase) InvalidateResourcePermissions(ctx context.Context, resource string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateResourcePermissions", ctx, resource)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateResourcePermissions indicates an expected call of InvalidateResourcePermissions.
func (mr *MockPermissionUseCaseMockRecorder) InvalidateResourcePermissions(ctx, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateResourcePermissions", reflect.TypeOf((*MockPermissionUseCase)(nil).InvalidateResourcePermissions), ctx, resource)
}

// InvalidateUserPermissions mocks base method.
func (m *MockPermissionUseCase) InvalidateUserPermissions(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InvalidateUserPermissions", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// InvalidateUserPermissions indicates an expected call of InvalidateUserPermissions.
func (mr *MockPermissionUseCaseMockRecorder) InvalidateUserPermissions(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InvalidateUserPermissions", reflect.TypeOf((*MockPermissionUseCase)(nil).InvalidateUserPermissions), ctx, userID)
}
