// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRankingHandler is a mock of RankingHandler interface.
type MockRankingHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRankingHandlerMockRecorder
	isgomock struct{}
}

// MockRankingHandlerMockRecorder is the mock recorder for MockRankingHandler.
type MockRankingHandlerMockRecorder struct {
	mock *MockRankingHandler
}

// NewMockRankingHandler creates a new mock instance.
func NewMockRankingHandler(ctrl *gomock.Controller) *MockRankingHandler {
	mock := &MockRankingHandler{ctrl: ctrl}
	mock.recorder = &MockRankingHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingHandler) EXPECT() *MockRankingHandlerMockRecorder {
	return m.recorder
}

// GetTop mocks base method.
func (m *MockRankingHandler) GetTop(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTop", c)
}

// GetTop indicates an expected call of GetTop.
func (mr *MockRankingHandlerMockRecorder) GetTop(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTop", reflect.TypeOf((*MockRankingHandler)(nil).GetTop), c)
}

// GetTrending mocks base method.
func (m *MockRankingHandler) GetTrending(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetTrending", c)
}

// GetTrending indicates an expected call of GetTrending.
func (mr *MockRankingHandlerMockRecorder) GetTrending(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrending", reflect.TypeOf((*MockRankingHandler)(nil).GetTrending), c)
}

// GetUserRanking mocks base method.
func (m *MockRankingHandler) GetUserRanking(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserRanking", c)
}

// GetUserRanking indicates an expected call of GetUserRanking.
func (mr *MockRankingHandlerMockRecorder) GetUserRanking(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRanking", reflect.TypeOf((*MockRankingHandler)(nil).GetUserRanking), c)
}

// RecalculateScores mocks base method.
func (m *MockRankingHandler) RecalculateScores(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RecalculateScores", c)
}

// RecalculateScores indicates an expected call of RecalculateScores.
func (mr *MockRankingHandlerMockRecorder) RecalculateScores(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecalculateScores", reflect.TypeOf((*MockRankingHandler)(nil).RecalculateScores), c)
}
