// Code generated by MockGen. DO NOT EDIT.
// Source: blog_version_repository.go
//
// Generated by this command:
//
//	mockgen -source=blog_version_repository.go -destination=mocks/mock_blog_version_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBlogVersionRepository is a mock of BlogVersionRepository interface.
type MockBlogVersionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBlogVersionRepositoryMockRecorder
	isgomock struct{}
}

// MockBlogVersionRepositoryMockRecorder is the mock recorder for MockBlogVersionRepository.
type MockBlogVersionRepositoryMockRecorder struct {
	mock *MockBlogVersionRepository
}

// NewMockBlogVersionRepository creates a new mock instance.
func NewMockBlogVersionRepository(ctrl *gomock.Controller) *MockBlogVersionRepository {
	mock := &MockBlogVersionRepository{ctrl: ctrl}
	mock.recorder = &MockBlogVersionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogVersionRepository) EXPECT() *MockBlogVersionRepositoryMockRecorder {
	return m.recorder
}

// CountByBlogID mocks base method.
func (m *MockBlogVersionRepository) CountByBlogID(ctx context.Context, blogID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByBlogID", ctx, blogID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByBlogID indicates an expected call of CountByBlogID.
func (mr *MockBlogVersionRepositoryMockRecorder) CountByBlogID(ctx, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByBlogID", reflect.TypeOf((*MockBlogVersionRepository)(nil).CountByBlogID), ctx, blogID)
}

// Create mocks base method.
func (m *MockBlogVersionRepository) Create(ctx context.Context, version *entity.BlogVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlogVersionRepositoryMockRecorder) Create(ctx, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlogVersionRepository)(nil).Create), ctx, version)
}

// Delete mocks base method.
func (m *MockBlogVersionRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogVersionRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogVersionRepository)(nil).Delete), ctx, id)
}

// DeleteOldest mocks base method.
func (m *MockBlogVersionRepository) DeleteOldest(ctx context.Context, blogID uuid.UUID, keep int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOldest", ctx, blogID, keep)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOldest indicates an expected call of DeleteOldest.
func (mr *MockBlogVersionRepositoryMockRecorder) DeleteOldest(ctx, blogID, keep any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOldest", reflect.TypeOf((*MockBlogVersionRepository)(nil).DeleteOldest), ctx, blogID, keep)
}

// FindByBlogID mocks base method.
func (m *MockBlogVersionRepository) FindByBlogID(ctx context.Context, blogID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.BlogVersion], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByBlogID", ctx, blogID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.BlogVersion])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByBlogID indicates an expected call of FindByBlogID.
func (mr *MockBlogVersionRepositoryMockRecorder) FindByBlogID(ctx, blogID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByBlogID", reflect.TypeOf((*MockBlogVersionRepository)(nil).FindByBlogID), ctx, blogID, pagination)
}

// FindByID mocks base method.
func (m *MockBlogVersionRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.BlogVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.BlogVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBlogVersionRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBlogVersionRepository)(nil).FindByID), ctx, id)
}

// GetNextVersionNumber mocks base method.
func (m *MockBlogVersionRepository) GetNextVersionNumber(ctx context.Context, blogID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetNextVersionNumber", ctx, blogID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetNextVersionNumber indicates an expected call of GetNextVersionNumber.
func (mr *MockBlogVersionRepositoryMockRecorder) GetNextVersionNumber(ctx, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetNextVersionNumber", reflect.TypeOf((*MockBlogVersionRepository)(nil).GetNextVersionNumber), ctx, blogID)
}
