// Code generated by MockGen. DO NOT EDIT.
// Source: tag_tier_mapping_repository.go
//
// Generated by this command:
//
//	mockgen -source=tag_tier_mapping_repository.go -destination=mocks/mock_tag_tier_mapping_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockTagTierMappingRepository is a mock of TagTierMappingRepository interface.
type MockTagTierMappingRepository struct {
	ctrl     *gomock.Controller
	recorder *MockTagTierMappingRepositoryMockRecorder
	isgomock struct{}
}

// MockTagTierMappingRepositoryMockRecorder is the mock recorder for MockTagTierMappingRepository.
type MockTagTierMappingRepositoryMockRecorder struct {
	mock *MockTagTierMappingRepository
}

// NewMockTagTierMappingRepository creates a new mock instance.
func NewMockTagTierMappingRepository(ctrl *gomock.Controller) *MockTagTierMappingRepository {
	mock := &MockTagTierMappingRepository{ctrl: ctrl}
	mock.recorder = &MockTagTierMappingRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTagTierMappingRepository) EXPECT() *MockTagTierMappingRepositoryMockRecorder {
	return m.recorder
}

// CountBlogsByTagAndAuthor mocks base method.
func (m *MockTagTierMappingRepository) CountBlogsByTagAndAuthor(ctx context.Context, authorID, tagID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlogsByTagAndAuthor", ctx, authorID, tagID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlogsByTagAndAuthor indicates an expected call of CountBlogsByTagAndAuthor.
func (mr *MockTagTierMappingRepositoryMockRecorder) CountBlogsByTagAndAuthor(ctx, authorID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlogsByTagAndAuthor", reflect.TypeOf((*MockTagTierMappingRepository)(nil).CountBlogsByTagAndAuthor), ctx, authorID, tagID)
}

// Create mocks base method.
func (m *MockTagTierMappingRepository) Create(ctx context.Context, mapping *entity.TagTierMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockTagTierMappingRepositoryMockRecorder) Create(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockTagTierMappingRepository)(nil).Create), ctx, mapping)
}

// Delete mocks base method.
func (m *MockTagTierMappingRepository) Delete(ctx context.Context, authorID, tagID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, authorID, tagID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockTagTierMappingRepositoryMockRecorder) Delete(ctx, authorID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockTagTierMappingRepository)(nil).Delete), ctx, authorID, tagID)
}

// DeleteByID mocks base method.
func (m *MockTagTierMappingRepository) DeleteByID(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByID", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByID indicates an expected call of DeleteByID.
func (mr *MockTagTierMappingRepositoryMockRecorder) DeleteByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByID", reflect.TypeOf((*MockTagTierMappingRepository)(nil).DeleteByID), ctx, id)
}

// FindByAuthor mocks base method.
func (m *MockTagTierMappingRepository) FindByAuthor(ctx context.Context, authorID uuid.UUID) ([]entity.TagTierMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthor", ctx, authorID)
	ret0, _ := ret[0].([]entity.TagTierMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthor indicates an expected call of FindByAuthor.
func (mr *MockTagTierMappingRepositoryMockRecorder) FindByAuthor(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthor", reflect.TypeOf((*MockTagTierMappingRepository)(nil).FindByAuthor), ctx, authorID)
}

// FindByAuthorAndTag mocks base method.
func (m *MockTagTierMappingRepository) FindByAuthorAndTag(ctx context.Context, authorID, tagID uuid.UUID) (*entity.TagTierMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthorAndTag", ctx, authorID, tagID)
	ret0, _ := ret[0].(*entity.TagTierMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthorAndTag indicates an expected call of FindByAuthorAndTag.
func (mr *MockTagTierMappingRepositoryMockRecorder) FindByAuthorAndTag(ctx, authorID, tagID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthorAndTag", reflect.TypeOf((*MockTagTierMappingRepository)(nil).FindByAuthorAndTag), ctx, authorID, tagID)
}

// FindByID mocks base method.
func (m *MockTagTierMappingRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.TagTierMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.TagTierMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockTagTierMappingRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockTagTierMappingRepository)(nil).FindByID), ctx, id)
}

// FindByTagIDs mocks base method.
func (m *MockTagTierMappingRepository) FindByTagIDs(ctx context.Context, authorID uuid.UUID, tagIDs []uuid.UUID) ([]entity.TagTierMapping, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByTagIDs", ctx, authorID, tagIDs)
	ret0, _ := ret[0].([]entity.TagTierMapping)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByTagIDs indicates an expected call of FindByTagIDs.
func (mr *MockTagTierMappingRepositoryMockRecorder) FindByTagIDs(ctx, authorID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByTagIDs", reflect.TypeOf((*MockTagTierMappingRepository)(nil).FindByTagIDs), ctx, authorID, tagIDs)
}

// Update mocks base method.
func (m *MockTagTierMappingRepository) Update(ctx context.Context, mapping *entity.TagTierMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockTagTierMappingRepositoryMockRecorder) Update(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockTagTierMappingRepository)(nil).Update), ctx, mapping)
}

// Upsert mocks base method.
func (m *MockTagTierMappingRepository) Upsert(ctx context.Context, mapping *entity.TagTierMapping) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, mapping)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockTagTierMappingRepositoryMockRecorder) Upsert(ctx, mapping any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockTagTierMappingRepository)(nil).Upsert), ctx, mapping)
}

// WithTx mocks base method.
func (m *MockTagTierMappingRepository) WithTx(tx any) repository.TagTierMappingRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.TagTierMappingRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockTagTierMappingRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockTagTierMappingRepository)(nil).WithTx), tx)
}
