// Code generated by MockGen. DO NOT EDIT.
// Source: reading_history_repository.go
//
// Generated by this command:
//
//	mockgen -source=reading_history_repository.go -destination=mocks/mock_reading_history_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReadingHistoryRepository is a mock of ReadingHistoryRepository interface.
type MockReadingHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockReadingHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockReadingHistoryRepositoryMockRecorder is the mock recorder for MockReadingHistoryRepository.
type MockReadingHistoryRepositoryMockRecorder struct {
	mock *MockReadingHistoryRepository
}

// NewMockReadingHistoryRepository creates a new mock instance.
func NewMockReadingHistoryRepository(ctrl *gomock.Controller) *MockReadingHistoryRepository {
	mock := &MockReadingHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockReadingHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingHistoryRepository) EXPECT() *MockReadingHistoryRepositoryMockRecorder {
	return m.recorder
}

// GetRecentByUserID mocks base method.
func (m *MockReadingHistoryRepository) GetRecentByUserID(ctx context.Context, userID uuid.UUID, limit int) ([]*entity.UserReadingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRecentByUserID", ctx, userID, limit)
	ret0, _ := ret[0].([]*entity.UserReadingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRecentByUserID indicates an expected call of GetRecentByUserID.
func (mr *MockReadingHistoryRepositoryMockRecorder) GetRecentByUserID(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRecentByUserID", reflect.TypeOf((*MockReadingHistoryRepository)(nil).GetRecentByUserID), ctx, userID, limit)
}

// Upsert mocks base method.
func (m *MockReadingHistoryRepository) Upsert(ctx context.Context, history *entity.UserReadingHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockReadingHistoryRepositoryMockRecorder) Upsert(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockReadingHistoryRepository)(nil).Upsert), ctx, history)
}
