// Code generated by MockGen. DO NOT EDIT.
// Source: bookmark_repository.go
//
// Generated by this command:
//
//	mockgen -source=bookmark_repository.go -destination=mocks/mock_bookmark_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBookmarkRepository is a mock of BookmarkRepository interface.
type MockBookmarkRepository struct {
	ctrl     *gomock.Controller
	recorder *MockBookmarkRepositoryMockRecorder
	isgomock struct{}
}

// MockBookmarkRepositoryMockRecorder is the mock recorder for MockBookmarkRepository.
type MockBookmarkRepositoryMockRecorder struct {
	mock *MockBookmarkRepository
}

// NewMockBookmarkRepository creates a new mock instance.
func NewMockBookmarkRepository(ctrl *gomock.Controller) *MockBookmarkRepository {
	mock := &MockBookmarkRepository{ctrl: ctrl}
	mock.recorder = &MockBookmarkRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBookmarkRepository) EXPECT() *MockBookmarkRepositoryMockRecorder {
	return m.recorder
}

// Add mocks base method.
func (m *MockBookmarkRepository) Add(ctx context.Context, userID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Add", ctx, userID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Add indicates an expected call of Add.
func (mr *MockBookmarkRepositoryMockRecorder) Add(ctx, userID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Add", reflect.TypeOf((*MockBookmarkRepository)(nil).Add), ctx, userID, blogID)
}

// CountByBlog mocks base method.
func (m *MockBookmarkRepository) CountByBlog(ctx context.Context, blogID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountByBlog", ctx, blogID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountByBlog indicates an expected call of CountByBlog.
func (mr *MockBookmarkRepositoryMockRecorder) CountByBlog(ctx, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountByBlog", reflect.TypeOf((*MockBookmarkRepository)(nil).CountByBlog), ctx, blogID)
}

// FindByUser mocks base method.
func (m *MockBookmarkRepository) FindByUser(ctx context.Context, userID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.Blog], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUser", ctx, userID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.Blog])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUser indicates an expected call of FindByUser.
func (mr *MockBookmarkRepositoryMockRecorder) FindByUser(ctx, userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUser", reflect.TypeOf((*MockBookmarkRepository)(nil).FindByUser), ctx, userID, pagination)
}

// IsBookmarked mocks base method.
func (m *MockBookmarkRepository) IsBookmarked(ctx context.Context, userID, blogID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsBookmarked", ctx, userID, blogID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// IsBookmarked indicates an expected call of IsBookmarked.
func (mr *MockBookmarkRepositoryMockRecorder) IsBookmarked(ctx, userID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsBookmarked", reflect.TypeOf((*MockBookmarkRepository)(nil).IsBookmarked), ctx, userID, blogID)
}

// Remove mocks base method.
func (m *MockBookmarkRepository) Remove(ctx context.Context, userID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", ctx, userID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockBookmarkRepositoryMockRecorder) Remove(ctx, userID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockBookmarkRepository)(nil).Remove), ctx, userID, blogID)
}
