// Code generated by MockGen. DO NOT EDIT.
// Source: subscription_plan_repository.go
//
// Generated by this command:
//
//	mockgen -source=subscription_plan_repository.go -destination=mocks/mock_subscription_plan_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionPlanRepository is a mock of SubscriptionPlanRepository interface.
type MockSubscriptionPlanRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionPlanRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionPlanRepositoryMockRecorder is the mock recorder for MockSubscriptionPlanRepository.
type MockSubscriptionPlanRepositoryMockRecorder struct {
	mock *MockSubscriptionPlanRepository
}

// NewMockSubscriptionPlanRepository creates a new mock instance.
func NewMockSubscriptionPlanRepository(ctrl *gomock.Controller) *MockSubscriptionPlanRepository {
	mock := &MockSubscriptionPlanRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionPlanRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionPlanRepository) EXPECT() *MockSubscriptionPlanRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSubscriptionPlanRepository) Create(ctx context.Context, plan *entity.SubscriptionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Create(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Create), ctx, plan)
}

// Delete mocks base method.
func (m *MockSubscriptionPlanRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Delete), ctx, id)
}

// FindActiveByAuthor mocks base method.
func (m *MockSubscriptionPlanRepository) FindActiveByAuthor(ctx context.Context, authorID uuid.UUID) ([]entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveByAuthor", ctx, authorID)
	ret0, _ := ret[0].([]entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveByAuthor indicates an expected call of FindActiveByAuthor.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) FindActiveByAuthor(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveByAuthor", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).FindActiveByAuthor), ctx, authorID)
}

// FindByAuthor mocks base method.
func (m *MockSubscriptionPlanRepository) FindByAuthor(ctx context.Context, authorID uuid.UUID) ([]entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthor", ctx, authorID)
	ret0, _ := ret[0].([]entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthor indicates an expected call of FindByAuthor.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) FindByAuthor(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthor", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).FindByAuthor), ctx, authorID)
}

// FindByAuthorAndTier mocks base method.
func (m *MockSubscriptionPlanRepository) FindByAuthorAndTier(ctx context.Context, authorID uuid.UUID, tier entity.SubscriptionTier) (*entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthorAndTier", ctx, authorID, tier)
	ret0, _ := ret[0].(*entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthorAndTier indicates an expected call of FindByAuthorAndTier.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) FindByAuthorAndTier(ctx, authorID, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthorAndTier", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).FindByAuthorAndTier), ctx, authorID, tier)
}

// FindByID mocks base method.
func (m *MockSubscriptionPlanRepository) FindByID(ctx context.Context, id uuid.UUID) (*entity.SubscriptionPlan, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*entity.SubscriptionPlan)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockSubscriptionPlanRepository) Update(ctx context.Context, plan *entity.SubscriptionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Update(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Update), ctx, plan)
}

// Upsert mocks base method.
func (m *MockSubscriptionPlanRepository) Upsert(ctx context.Context, plan *entity.SubscriptionPlan) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, plan)
	ret0, _ := ret[0].(error)
	return ret0
}

// Upsert indicates an expected call of Upsert.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) Upsert(ctx, plan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).Upsert), ctx, plan)
}

// WithTx mocks base method.
func (m *MockSubscriptionPlanRepository) WithTx(tx any) repository.SubscriptionPlanRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.SubscriptionPlanRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockSubscriptionPlanRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockSubscriptionPlanRepository)(nil).WithTx), tx)
}
