// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/repository/user_series_purchase_repository.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/repository/user_series_purchase_repository.go -destination=internal/domain/repository/mocks/mock_user_series_purchase_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserSeriesPurchaseRepository is a mock of UserSeriesPurchaseRepository interface.
type MockUserSeriesPurchaseRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserSeriesPurchaseRepositoryMockRecorder
	isgomock struct{}
}

// MockUserSeriesPurchaseRepositoryMockRecorder is the mock recorder for MockUserSeriesPurchaseRepository.
type MockUserSeriesPurchaseRepositoryMockRecorder struct {
	mock *MockUserSeriesPurchaseRepository
}

// NewMockUserSeriesPurchaseRepository creates a new mock instance.
func NewMockUserSeriesPurchaseRepository(ctrl *gomock.Controller) *MockUserSeriesPurchaseRepository {
	mock := &MockUserSeriesPurchaseRepository{ctrl: ctrl}
	mock.recorder = &MockUserSeriesPurchaseRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserSeriesPurchaseRepository) EXPECT() *MockUserSeriesPurchaseRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserSeriesPurchaseRepository) Create(ctx context.Context, purchase *entity.UserSeriesPurchase) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, purchase)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserSeriesPurchaseRepositoryMockRecorder) Create(ctx, purchase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserSeriesPurchaseRepository)(nil).Create), ctx, purchase)
}

// GetUserPurchases mocks base method.
func (m *MockUserSeriesPurchaseRepository) GetUserPurchases(ctx context.Context, userID uuid.UUID) ([]*entity.UserSeriesPurchase, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPurchases", ctx, userID)
	ret0, _ := ret[0].([]*entity.UserSeriesPurchase)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPurchases indicates an expected call of GetUserPurchases.
func (mr *MockUserSeriesPurchaseRepositoryMockRecorder) GetUserPurchases(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPurchases", reflect.TypeOf((*MockUserSeriesPurchaseRepository)(nil).GetUserPurchases), ctx, userID)
}

// HasPurchased mocks base method.
func (m *MockUserSeriesPurchaseRepository) HasPurchased(ctx context.Context, userID, seriesID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPurchased", ctx, userID, seriesID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HasPurchased indicates an expected call of HasPurchased.
func (mr *MockUserSeriesPurchaseRepositoryMockRecorder) HasPurchased(ctx, userID, seriesID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPurchased", reflect.TypeOf((*MockUserSeriesPurchaseRepository)(nil).HasPurchased), ctx, userID, seriesID)
}

// WithTx mocks base method.
func (m *MockUserSeriesPurchaseRepository) WithTx(tx any) repository.UserSeriesPurchaseRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.UserSeriesPurchaseRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockUserSeriesPurchaseRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockUserSeriesPurchaseRepository)(nil).WithTx), tx)
}
