// Code generated by MockGen. DO NOT EDIT.
// Source: social_account_repository.go
//
// Generated by this command:
//
//	mockgen -source=social_account_repository.go -destination=mocks/mock_social_account_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSocialAccountRepository is a mock of SocialAccountRepository interface.
type MockSocialAccountRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSocialAccountRepositoryMockRecorder
	isgomock struct{}
}

// MockSocialAccountRepositoryMockRecorder is the mock recorder for MockSocialAccountRepository.
type MockSocialAccountRepositoryMockRecorder struct {
	mock *MockSocialAccountRepository
}

// NewMockSocialAccountRepository creates a new mock instance.
func NewMockSocialAccountRepository(ctrl *gomock.Controller) *MockSocialAccountRepository {
	mock := &MockSocialAccountRepository{ctrl: ctrl}
	mock.recorder = &MockSocialAccountRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialAccountRepository) EXPECT() *MockSocialAccountRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockSocialAccountRepository) Create(ctx context.Context, socialAccount *entity.SocialAccount) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, socialAccount)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSocialAccountRepositoryMockRecorder) Create(ctx, socialAccount any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSocialAccountRepository)(nil).Create), ctx, socialAccount)
}

// FindByProvider mocks base method.
func (m *MockSocialAccountRepository) FindByProvider(ctx context.Context, provider, providerID string) (*entity.SocialAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByProvider", ctx, provider, providerID)
	ret0, _ := ret[0].(*entity.SocialAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByProvider indicates an expected call of FindByProvider.
func (mr *MockSocialAccountRepositoryMockRecorder) FindByProvider(ctx, provider, providerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByProvider", reflect.TypeOf((*MockSocialAccountRepository)(nil).FindByProvider), ctx, provider, providerID)
}

// GetByUserID mocks base method.
func (m *MockSocialAccountRepository) GetByUserID(ctx context.Context, userID uuid.UUID) ([]*entity.SocialAccount, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByUserID", ctx, userID)
	ret0, _ := ret[0].([]*entity.SocialAccount)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByUserID indicates an expected call of GetByUserID.
func (mr *MockSocialAccountRepositoryMockRecorder) GetByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByUserID", reflect.TypeOf((*MockSocialAccountRepository)(nil).GetByUserID), ctx, userID)
}
