// Code generated by MockGen. DO NOT EDIT.
// Source: subscription_repository.go
//
// Generated by this command:
//
//	mockgen -source=subscription_repository.go -destination=mocks/mock_subscription_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionRepository is a mock of SubscriptionRepository interface.
type MockSubscriptionRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionRepositoryMockRecorder
	isgomock struct{}
}

// MockSubscriptionRepositoryMockRecorder is the mock recorder for MockSubscriptionRepository.
type MockSubscriptionRepositoryMockRecorder struct {
	mock *MockSubscriptionRepository
}

// NewMockSubscriptionRepository creates a new mock instance.
func NewMockSubscriptionRepository(ctrl *gomock.Controller) *MockSubscriptionRepository {
	mock := &MockSubscriptionRepository{ctrl: ctrl}
	mock.recorder = &MockSubscriptionRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionRepository) EXPECT() *MockSubscriptionRepositoryMockRecorder {
	return m.recorder
}

// CountBySubscriber mocks base method.
func (m *MockSubscriptionRepository) CountBySubscriber(ctx context.Context, subscriberID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBySubscriber", ctx, subscriberID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBySubscriber indicates an expected call of CountBySubscriber.
func (mr *MockSubscriptionRepositoryMockRecorder) CountBySubscriber(ctx, subscriberID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBySubscriber", reflect.TypeOf((*MockSubscriptionRepository)(nil).CountBySubscriber), ctx, subscriberID)
}

// CountSubscribers mocks base method.
func (m *MockSubscriptionRepository) CountSubscribers(ctx context.Context, authorID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountSubscribers", ctx, authorID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountSubscribers indicates an expected call of CountSubscribers.
func (mr *MockSubscriptionRepositoryMockRecorder) CountSubscribers(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscribers", reflect.TypeOf((*MockSubscriptionRepository)(nil).CountSubscribers), ctx, authorID)
}

// Create mocks base method.
func (m *MockSubscriptionRepository) Create(ctx context.Context, subscription *entity.Subscription) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, subscription)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSubscriptionRepositoryMockRecorder) Create(ctx, subscription any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSubscriptionRepository)(nil).Create), ctx, subscription)
}

// Delete mocks base method.
func (m *MockSubscriptionRepository) Delete(ctx context.Context, subscriberID, authorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, subscriberID, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSubscriptionRepositoryMockRecorder) Delete(ctx, subscriberID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSubscriptionRepository)(nil).Delete), ctx, subscriberID, authorID)
}

// Exists mocks base method.
func (m *MockSubscriptionRepository) Exists(ctx context.Context, subscriberID, authorID uuid.UUID) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Exists", ctx, subscriberID, authorID)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Exists indicates an expected call of Exists.
func (mr *MockSubscriptionRepositoryMockRecorder) Exists(ctx, subscriberID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Exists", reflect.TypeOf((*MockSubscriptionRepository)(nil).Exists), ctx, subscriberID, authorID)
}

// FindActiveSubscription mocks base method.
func (m *MockSubscriptionRepository) FindActiveSubscription(ctx context.Context, userID, authorID uuid.UUID) (*entity.Subscription, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindActiveSubscription", ctx, userID, authorID)
	ret0, _ := ret[0].(*entity.Subscription)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindActiveSubscription indicates an expected call of FindActiveSubscription.
func (mr *MockSubscriptionRepositoryMockRecorder) FindActiveSubscription(ctx, userID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindActiveSubscription", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindActiveSubscription), ctx, userID, authorID)
}

// FindByAuthor mocks base method.
func (m *MockSubscriptionRepository) FindByAuthor(ctx context.Context, authorID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.Subscription], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByAuthor", ctx, authorID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.Subscription])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByAuthor indicates an expected call of FindByAuthor.
func (mr *MockSubscriptionRepositoryMockRecorder) FindByAuthor(ctx, authorID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByAuthor", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindByAuthor), ctx, authorID, pagination)
}

// FindBySubscriber mocks base method.
func (m *MockSubscriptionRepository) FindBySubscriber(ctx context.Context, subscriberID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.Subscription], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindBySubscriber", ctx, subscriberID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.Subscription])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindBySubscriber indicates an expected call of FindBySubscriber.
func (mr *MockSubscriptionRepositoryMockRecorder) FindBySubscriber(ctx, subscriberID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindBySubscriber", reflect.TypeOf((*MockSubscriptionRepository)(nil).FindBySubscriber), ctx, subscriberID, pagination)
}

// UpdateExpiry mocks base method.
func (m *MockSubscriptionRepository) UpdateExpiry(ctx context.Context, userID, authorID uuid.UUID, expiresAt time.Time, tier string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateExpiry", ctx, userID, authorID, expiresAt, tier)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateExpiry indicates an expected call of UpdateExpiry.
func (mr *MockSubscriptionRepositoryMockRecorder) UpdateExpiry(ctx, userID, authorID, expiresAt, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateExpiry", reflect.TypeOf((*MockSubscriptionRepository)(nil).UpdateExpiry), ctx, userID, authorID, expiresAt, tier)
}

// WithTx mocks base method.
func (m *MockSubscriptionRepository) WithTx(tx any) repository.SubscriptionRepository {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WithTx", tx)
	ret0, _ := ret[0].(repository.SubscriptionRepository)
	return ret0
}

// WithTx indicates an expected call of WithTx.
func (mr *MockSubscriptionRepositoryMockRecorder) WithTx(tx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WithTx", reflect.TypeOf((*MockSubscriptionRepository)(nil).WithTx), tx)
}
