// Code generated by MockGen. DO NOT EDIT.
// Source: base.go
//
// Generated by this command:
//
//	mockgen -source=base.go -destination=mocks/mock_base.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBaseRepository is a mock of BaseRepository interface.
type MockBaseRepository[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockBaseRepositoryMockRecorder[T]
	isgomock struct{}
}

// MockBaseRepositoryMockRecorder is the mock recorder for MockBaseRepository.
type MockBaseRepositoryMockRecorder[T any] struct {
	mock *MockBaseRepository[T]
}

// NewMockBaseRepository creates a new mock instance.
func NewMockBaseRepository[T any](ctrl *gomock.Controller) *MockBaseRepository[T] {
	mock := &MockBaseRepository[T]{ctrl: ctrl}
	mock.recorder = &MockBaseRepositoryMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBaseRepository[T]) EXPECT() *MockBaseRepositoryMockRecorder[T] {
	return m.recorder
}

// Create mocks base method.
func (m *MockBaseRepository[T]) Create(ctx context.Context, entity *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBaseRepositoryMockRecorder[T]) Create(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBaseRepository[T])(nil).Create), ctx, entity)
}

// Delete mocks base method.
func (m *MockBaseRepository[T]) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBaseRepositoryMockRecorder[T]) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBaseRepository[T])(nil).Delete), ctx, id)
}

// FindAll mocks base method.
func (m *MockBaseRepository[T]) FindAll(ctx context.Context, pagination repository.Pagination) (*repository.PaginatedResult[T], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAll", ctx, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[T])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAll indicates an expected call of FindAll.
func (mr *MockBaseRepositoryMockRecorder[T]) FindAll(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAll", reflect.TypeOf((*MockBaseRepository[T])(nil).FindAll), ctx, pagination)
}

// FindByID mocks base method.
func (m *MockBaseRepository[T]) FindByID(ctx context.Context, id uuid.UUID) (*T, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByID", ctx, id)
	ret0, _ := ret[0].(*T)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByID indicates an expected call of FindByID.
func (mr *MockBaseRepositoryMockRecorder[T]) FindByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByID", reflect.TypeOf((*MockBaseRepository[T])(nil).FindByID), ctx, id)
}

// Update mocks base method.
func (m *MockBaseRepository[T]) Update(ctx context.Context, entity *T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, entity)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBaseRepositoryMockRecorder[T]) Update(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBaseRepository[T])(nil).Update), ctx, entity)
}
