// Code generated by MockGen. DO NOT EDIT.
// Source: system_repository.go
//
// Generated by this command:
//
//	mockgen -source=system_repository.go -destination=mocks/mock_system_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSystemRepository is a mock of SystemRepository interface.
type MockSystemRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSystemRepositoryMockRecorder
	isgomock struct{}
}

// MockSystemRepositoryMockRecorder is the mock recorder for MockSystemRepository.
type MockSystemRepositoryMockRecorder struct {
	mock *MockSystemRepository
}

// NewMockSystemRepository creates a new mock instance.
func NewMockSystemRepository(ctrl *gomock.Controller) *MockSystemRepository {
	mock := &MockSystemRepository{ctrl: ctrl}
	mock.recorder = &MockSystemRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemRepository) EXPECT() *MockSystemRepositoryMockRecorder {
	return m.recorder
}

// CheckDatabase mocks base method.
func (m *MockSystemRepository) CheckDatabase(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckDatabase", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckDatabase indicates an expected call of CheckDatabase.
func (mr *MockSystemRepositoryMockRecorder) CheckDatabase(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckDatabase", reflect.TypeOf((*MockSystemRepository)(nil).CheckDatabase), ctx)
}

// CheckRedis mocks base method.
func (m *MockSystemRepository) CheckRedis(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckRedis", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckRedis indicates an expected call of CheckRedis.
func (mr *MockSystemRepositoryMockRecorder) CheckRedis(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckRedis", reflect.TypeOf((*MockSystemRepository)(nil).CheckRedis), ctx)
}
