// Code generated by MockGen. DO NOT EDIT.
// Source: user_ranking_repository.go
//
// Generated by this command:
//
//	mockgen -source=user_ranking_repository.go -destination=mocks/mock_user_ranking_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockUserVelocityScoreRepository is a mock of UserVelocityScoreRepository interface.
type MockUserVelocityScoreRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserVelocityScoreRepositoryMockRecorder
	isgomock struct{}
}

// MockUserVelocityScoreRepositoryMockRecorder is the mock recorder for MockUserVelocityScoreRepository.
type MockUserVelocityScoreRepositoryMockRecorder struct {
	mock *MockUserVelocityScoreRepository
}

// NewMockUserVelocityScoreRepository creates a new mock instance.
func NewMockUserVelocityScoreRepository(ctrl *gomock.Controller) *MockUserVelocityScoreRepository {
	mock := &MockUserVelocityScoreRepository{ctrl: ctrl}
	mock.recorder = &MockUserVelocityScoreRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserVelocityScoreRepository) EXPECT() *MockUserVelocityScoreRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockUserVelocityScoreRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).Count), ctx)
}

// DeleteByUserID mocks base method.
func (m *MockUserVelocityScoreRepository) DeleteByUserID(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByUserID", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByUserID indicates an expected call of DeleteByUserID.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) DeleteByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByUserID", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).DeleteByUserID), ctx, userID)
}

// FindByRank mocks base method.
func (m *MockUserVelocityScoreRepository) FindByRank(ctx context.Context, rank int) (*entity.UserVelocityScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByRank", ctx, rank)
	ret0, _ := ret[0].(*entity.UserVelocityScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByRank indicates an expected call of FindByRank.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) FindByRank(ctx, rank any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByRank", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).FindByRank), ctx, rank)
}

// FindByUserID mocks base method.
func (m *MockUserVelocityScoreRepository) FindByUserID(ctx context.Context, userID uuid.UUID) (*entity.UserVelocityScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserVelocityScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) FindByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).FindByUserID), ctx, userID)
}

// ListRanked mocks base method.
func (m *MockUserVelocityScoreRepository) ListRanked(ctx context.Context, pagination repository.Pagination) (*repository.PaginatedResult[entity.UserVelocityScore], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRanked", ctx, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.UserVelocityScore])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRanked indicates an expected call of ListRanked.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) ListRanked(ctx, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRanked", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).ListRanked), ctx, pagination)
}

// ListTopRanked mocks base method.
func (m *MockUserVelocityScoreRepository) ListTopRanked(ctx context.Context, limit int) ([]entity.UserVelocityScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListTopRanked", ctx, limit)
	ret0, _ := ret[0].([]entity.UserVelocityScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListTopRanked indicates an expected call of ListTopRanked.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) ListTopRanked(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListTopRanked", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).ListTopRanked), ctx, limit)
}

// Save mocks base method.
func (m *MockUserVelocityScoreRepository) Save(ctx context.Context, score *entity.UserVelocityScore) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", ctx, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) Save(ctx, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).Save), ctx, score)
}

// UpdateRankPosition mocks base method.
func (m *MockUserVelocityScoreRepository) UpdateRankPosition(ctx context.Context, userID uuid.UUID, rank int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRankPosition", ctx, userID, rank)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateRankPosition indicates an expected call of UpdateRankPosition.
func (mr *MockUserVelocityScoreRepositoryMockRecorder) UpdateRankPosition(ctx, userID, rank any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRankPosition", reflect.TypeOf((*MockUserVelocityScoreRepository)(nil).UpdateRankPosition), ctx, userID, rank)
}

// MockUserRankingHistoryRepository is a mock of UserRankingHistoryRepository interface.
type MockUserRankingHistoryRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserRankingHistoryRepositoryMockRecorder
	isgomock struct{}
}

// MockUserRankingHistoryRepositoryMockRecorder is the mock recorder for MockUserRankingHistoryRepository.
type MockUserRankingHistoryRepositoryMockRecorder struct {
	mock *MockUserRankingHistoryRepository
}

// NewMockUserRankingHistoryRepository creates a new mock instance.
func NewMockUserRankingHistoryRepository(ctrl *gomock.Controller) *MockUserRankingHistoryRepository {
	mock := &MockUserRankingHistoryRepository{ctrl: ctrl}
	mock.recorder = &MockUserRankingHistoryRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserRankingHistoryRepository) EXPECT() *MockUserRankingHistoryRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockUserRankingHistoryRepository) Create(ctx context.Context, history *entity.UserRankingHistory) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, history)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserRankingHistoryRepositoryMockRecorder) Create(ctx, history any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserRankingHistoryRepository)(nil).Create), ctx, history)
}

// FindByUserID mocks base method.
func (m *MockUserRankingHistoryRepository) FindByUserID(ctx context.Context, userID uuid.UUID, limit int) ([]entity.UserRankingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserID", ctx, userID, limit)
	ret0, _ := ret[0].([]entity.UserRankingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserID indicates an expected call of FindByUserID.
func (mr *MockUserRankingHistoryRepositoryMockRecorder) FindByUserID(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserID", reflect.TypeOf((*MockUserRankingHistoryRepository)(nil).FindByUserID), ctx, userID, limit)
}

// FindLatestByUserID mocks base method.
func (m *MockUserRankingHistoryRepository) FindLatestByUserID(ctx context.Context, userID uuid.UUID) (*entity.UserRankingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserRankingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByUserID indicates an expected call of FindLatestByUserID.
func (mr *MockUserRankingHistoryRepositoryMockRecorder) FindLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByUserID", reflect.TypeOf((*MockUserRankingHistoryRepository)(nil).FindLatestByUserID), ctx, userID)
}

// ListByDateRange mocks base method.
func (m *MockUserRankingHistoryRepository) ListByDateRange(ctx context.Context, userID uuid.UUID, startDate, endDate time.Time) ([]entity.UserRankingHistory, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByDateRange", ctx, userID, startDate, endDate)
	ret0, _ := ret[0].([]entity.UserRankingHistory)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByDateRange indicates an expected call of ListByDateRange.
func (mr *MockUserRankingHistoryRepositoryMockRecorder) ListByDateRange(ctx, userID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByDateRange", reflect.TypeOf((*MockUserRankingHistoryRepository)(nil).ListByDateRange), ctx, userID, startDate, endDate)
}

// MockUserFollowerSnapshotRepository is a mock of UserFollowerSnapshotRepository interface.
type MockUserFollowerSnapshotRepository struct {
	ctrl     *gomock.Controller
	recorder *MockUserFollowerSnapshotRepositoryMockRecorder
	isgomock struct{}
}

// MockUserFollowerSnapshotRepositoryMockRecorder is the mock recorder for MockUserFollowerSnapshotRepository.
type MockUserFollowerSnapshotRepositoryMockRecorder struct {
	mock *MockUserFollowerSnapshotRepository
}

// NewMockUserFollowerSnapshotRepository creates a new mock instance.
func NewMockUserFollowerSnapshotRepository(ctrl *gomock.Controller) *MockUserFollowerSnapshotRepository {
	mock := &MockUserFollowerSnapshotRepository{ctrl: ctrl}
	mock.recorder = &MockUserFollowerSnapshotRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserFollowerSnapshotRepository) EXPECT() *MockUserFollowerSnapshotRepositoryMockRecorder {
	return m.recorder
}

// CountBlogs mocks base method.
func (m *MockUserFollowerSnapshotRepository) CountBlogs(ctx context.Context, userID uuid.UUID, startDate, endDate time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountBlogs", ctx, userID, startDate, endDate)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountBlogs indicates an expected call of CountBlogs.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) CountBlogs(ctx, userID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountBlogs", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).CountBlogs), ctx, userID, startDate, endDate)
}

// CountFollowers mocks base method.
func (m *MockUserFollowerSnapshotRepository) CountFollowers(ctx context.Context, userID uuid.UUID) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CountFollowers", ctx, userID)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CountFollowers indicates an expected call of CountFollowers.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) CountFollowers(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountFollowers", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).CountFollowers), ctx, userID)
}

// Create mocks base method.
func (m *MockUserFollowerSnapshotRepository) Create(ctx context.Context, snapshot *entity.UserFollowerSnapshot) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, snapshot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) Create(ctx, snapshot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).Create), ctx, snapshot)
}

// FindByUserIDAndDate mocks base method.
func (m *MockUserFollowerSnapshotRepository) FindByUserIDAndDate(ctx context.Context, userID uuid.UUID, date time.Time) (*entity.UserFollowerSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndDate", ctx, userID, date)
	ret0, _ := ret[0].(*entity.UserFollowerSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndDate indicates an expected call of FindByUserIDAndDate.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) FindByUserIDAndDate(ctx, userID, date any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndDate", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).FindByUserIDAndDate), ctx, userID, date)
}

// FindByUserIDAndDateRange mocks base method.
func (m *MockUserFollowerSnapshotRepository) FindByUserIDAndDateRange(ctx context.Context, userID uuid.UUID, startDate, endDate time.Time) ([]entity.UserFollowerSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindByUserIDAndDateRange", ctx, userID, startDate, endDate)
	ret0, _ := ret[0].([]entity.UserFollowerSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindByUserIDAndDateRange indicates an expected call of FindByUserIDAndDateRange.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) FindByUserIDAndDateRange(ctx, userID, startDate, endDate any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindByUserIDAndDateRange", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).FindByUserIDAndDateRange), ctx, userID, startDate, endDate)
}

// FindLatestByUserID mocks base method.
func (m *MockUserFollowerSnapshotRepository) FindLatestByUserID(ctx context.Context, userID uuid.UUID) (*entity.UserFollowerSnapshot, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindLatestByUserID", ctx, userID)
	ret0, _ := ret[0].(*entity.UserFollowerSnapshot)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindLatestByUserID indicates an expected call of FindLatestByUserID.
func (mr *MockUserFollowerSnapshotRepositoryMockRecorder) FindLatestByUserID(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindLatestByUserID", reflect.TypeOf((*MockUserFollowerSnapshotRepository)(nil).FindLatestByUserID), ctx, userID)
}
