// Code generated by MockGen. DO NOT EDIT.
// Source: series_repository.go
//
// Generated by this command:
//
//	mockgen -source=series_repository.go -destination=mocks/mock_series_repository.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesRepository is a mock of SeriesRepository interface.
type MockSeriesRepository struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesRepositoryMockRecorder
	isgomock struct{}
}

// MockSeriesRepositoryMockRecorder is the mock recorder for MockSeriesRepository.
type MockSeriesRepositoryMockRecorder struct {
	mock *MockSeriesRepository
}

// NewMockSeriesRepository creates a new mock instance.
func NewMockSeriesRepository(ctrl *gomock.Controller) *MockSeriesRepository {
	mock := &MockSeriesRepository{ctrl: ctrl}
	mock.recorder = &MockSeriesRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesRepository) EXPECT() *MockSeriesRepositoryMockRecorder {
	return m.recorder
}

// AddBlog mocks base method.
func (m *MockSeriesRepository) AddBlog(ctx context.Context, seriesID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBlog", ctx, seriesID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBlog indicates an expected call of AddBlog.
func (mr *MockSeriesRepositoryMockRecorder) AddBlog(ctx, seriesID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlog", reflect.TypeOf((*MockSeriesRepository)(nil).AddBlog), ctx, seriesID, blogID)
}

// Create mocks base method.
func (m *MockSeriesRepository) Create(ctx context.Context, series *entity.Series) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, series)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockSeriesRepositoryMockRecorder) Create(ctx, series any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockSeriesRepository)(nil).Create), ctx, series)
}

// Delete mocks base method.
func (m *MockSeriesRepository) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockSeriesRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockSeriesRepository)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockSeriesRepository) GetByID(ctx context.Context, id uuid.UUID) (*entity.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entity.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockSeriesRepositoryMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockSeriesRepository)(nil).GetByID), ctx, id)
}

// GetBySlug mocks base method.
func (m *MockSeriesRepository) GetBySlug(ctx context.Context, slug string) (*entity.Series, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, slug)
	ret0, _ := ret[0].(*entity.Series)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockSeriesRepositoryMockRecorder) GetBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockSeriesRepository)(nil).GetBySlug), ctx, slug)
}

// GetHighlighted mocks base method.
func (m *MockSeriesRepository) GetHighlighted(ctx context.Context, limit int) ([]repository.HighlightedSeriesResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighlighted", ctx, limit)
	ret0, _ := ret[0].([]repository.HighlightedSeriesResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighlighted indicates an expected call of GetHighlighted.
func (mr *MockSeriesRepositoryMockRecorder) GetHighlighted(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighlighted", reflect.TypeOf((*MockSeriesRepository)(nil).GetHighlighted), ctx, limit)
}

// List mocks base method.
func (m *MockSeriesRepository) List(ctx context.Context, params map[string]any) ([]entity.Series, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, params)
	ret0, _ := ret[0].([]entity.Series)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// List indicates an expected call of List.
func (mr *MockSeriesRepositoryMockRecorder) List(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockSeriesRepository)(nil).List), ctx, params)
}

// RemoveBlog mocks base method.
func (m *MockSeriesRepository) RemoveBlog(ctx context.Context, seriesID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBlog", ctx, seriesID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBlog indicates an expected call of RemoveBlog.
func (mr *MockSeriesRepositoryMockRecorder) RemoveBlog(ctx, seriesID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBlog", reflect.TypeOf((*MockSeriesRepository)(nil).RemoveBlog), ctx, seriesID, blogID)
}

// Update mocks base method.
func (m *MockSeriesRepository) Update(ctx context.Context, series *entity.Series) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, series)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockSeriesRepositoryMockRecorder) Update(ctx, series any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockSeriesRepository)(nil).Update), ctx, series)
}
