// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockRecommendationHandler is a mock of RecommendationHandler interface.
type MockRecommendationHandler struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationHandlerMockRecorder
	isgomock struct{}
}

// MockRecommendationHandlerMockRecorder is the mock recorder for MockRecommendationHandler.
type MockRecommendationHandlerMockRecorder struct {
	mock *MockRecommendationHandler
}

// NewMockRecommendationHandler creates a new mock instance.
func NewMockRecommendationHandler(ctrl *gomock.Controller) *MockRecommendationHandler {
	mock := &MockRecommendationHandler{ctrl: ctrl}
	mock.recorder = &MockRecommendationHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationHandler) EXPECT() *MockRecommendationHandlerMockRecorder {
	return m.recorder
}

// GetPersonalizedFeed mocks base method.
func (m *MockRecommendationHandler) GetPersonalizedFeed(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPersonalizedFeed", c)
}

// GetPersonalizedFeed indicates an expected call of GetPersonalizedFeed.
func (mr *MockRecommendationHandlerMockRecorder) GetPersonalizedFeed(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalizedFeed", reflect.TypeOf((*MockRecommendationHandler)(nil).GetPersonalizedFeed), c)
}

// GetPopularTags mocks base method.
func (m *MockRecommendationHandler) GetPopularTags(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetPopularTags", c)
}

// GetPopularTags indicates an expected call of GetPopularTags.
func (mr *MockRecommendationHandlerMockRecorder) GetPopularTags(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularTags", reflect.TypeOf((*MockRecommendationHandler)(nil).GetPopularTags), c)
}

// GetRelatedBlogs mocks base method.
func (m *MockRecommendationHandler) GetRelatedBlogs(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetRelatedBlogs", c)
}

// GetRelatedBlogs indicates an expected call of GetRelatedBlogs.
func (mr *MockRecommendationHandlerMockRecorder) GetRelatedBlogs(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedBlogs", reflect.TypeOf((*MockRecommendationHandler)(nil).GetRelatedBlogs), c)
}

// UpdateInterests mocks base method.
func (m *MockRecommendationHandler) UpdateInterests(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateInterests", c)
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockRecommendationHandlerMockRecorder) UpdateInterests(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockRecommendationHandler)(nil).UpdateInterests), c)
}
