// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/usecase/payment/process_webhook.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/usecase/payment/process_webhook.go -destination=internal/application/usecase/payment/mocks/mock_process_webhook.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	entity "github.com/aiagent/internal/domain/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockProcessWebhookUseCase is a mock of ProcessWebhookUseCase interface.
type MockProcessWebhookUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockProcessWebhookUseCaseMockRecorder
	isgomock struct{}
}

// MockProcessWebhookUseCaseMockRecorder is the mock recorder for MockProcessWebhookUseCase.
type MockProcessWebhookUseCaseMockRecorder struct {
	mock *MockProcessWebhookUseCase
}

// NewMockProcessWebhookUseCase creates a new mock instance.
func NewMockProcessWebhookUseCase(ctrl *gomock.Controller) *MockProcessWebhookUseCase {
	mock := &MockProcessWebhookUseCase{ctrl: ctrl}
	mock.recorder = &MockProcessWebhookUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessWebhookUseCase) EXPECT() *MockProcessWebhookUseCaseMockRecorder {
	return m.recorder
}

// Execute mocks base method.
func (m *MockProcessWebhookUseCase) Execute(ctx context.Context, req dto.ProcessWebhookRequest) (*entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Execute", ctx, req)
	ret0, _ := ret[0].(*entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Execute indicates an expected call of Execute.
func (mr *MockProcessWebhookUseCaseMockRecorder) Execute(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Execute", reflect.TypeOf((*MockProcessWebhookUseCase)(nil).Execute), ctx, req)
}
