// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	entity "github.com/aiagent/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRoleUseCase is a mock of RoleUseCase interface.
type MockRoleUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockRoleUseCaseMockRecorder
	isgomock struct{}
}

// MockRoleUseCaseMockRecorder is the mock recorder for MockRoleUseCase.
type MockRoleUseCaseMockRecorder struct {
	mock *MockRoleUseCase
}

// NewMockRoleUseCase creates a new mock instance.
func NewMockRoleUseCase(ctrl *gomock.Controller) *MockRoleUseCase {
	mock := &MockRoleUseCase{ctrl: ctrl}
	mock.recorder = &MockRoleUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRoleUseCase) EXPECT() *MockRoleUseCaseMockRecorder {
	return m.recorder
}

// AssignRole mocks base method.
func (m *MockRoleUseCase) AssignRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRole indicates an expected call of AssignRole.
func (mr *MockRoleUseCaseMockRecorder) AssignRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRole", reflect.TypeOf((*MockRoleUseCase)(nil).AssignRole), ctx, userID, roleID)
}

// CheckPermission mocks base method.
func (m *MockRoleUseCase) CheckPermission(ctx context.Context, userID uuid.UUID, resource string, permission entity.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, resource, permission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockRoleUseCaseMockRecorder) CheckPermission(ctx, userID, resource, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockRoleUseCase)(nil).CheckPermission), ctx, userID, resource, permission)
}

// CreateRole mocks base method.
func (m *MockRoleUseCase) CreateRole(ctx context.Context, req dto.CreateRoleRequest) (*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateRole", ctx, req)
	ret0, _ := ret[0].(*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateRole indicates an expected call of CreateRole.
func (mr *MockRoleUseCaseMockRecorder) CreateRole(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateRole", reflect.TypeOf((*MockRoleUseCase)(nil).CreateRole), ctx, req)
}

// DeleteRole mocks base method.
func (m *MockRoleUseCase) DeleteRole(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteRole", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteRole indicates an expected call of DeleteRole.
func (mr *MockRoleUseCaseMockRecorder) DeleteRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteRole", reflect.TypeOf((*MockRoleUseCase)(nil).DeleteRole), ctx, id)
}

// GetRole mocks base method.
func (m *MockRoleUseCase) GetRole(ctx context.Context, id uuid.UUID) (*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRole", ctx, id)
	ret0, _ := ret[0].(*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRole indicates an expected call of GetRole.
func (mr *MockRoleUseCaseMockRecorder) GetRole(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRole", reflect.TypeOf((*MockRoleUseCase)(nil).GetRole), ctx, id)
}

// GetUserPermission mocks base method.
func (m *MockRoleUseCase) GetUserPermission(ctx context.Context, userID uuid.UUID, resource string) (*dto.UserPermissionResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermission", ctx, userID, resource)
	ret0, _ := ret[0].(*dto.UserPermissionResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermission indicates an expected call of GetUserPermission.
func (mr *MockRoleUseCaseMockRecorder) GetUserPermission(ctx, userID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermission", reflect.TypeOf((*MockRoleUseCase)(nil).GetUserPermission), ctx, userID, resource)
}

// GetUserRoles mocks base method.
func (m *MockRoleUseCase) GetUserRoles(ctx context.Context, userID uuid.UUID) (*dto.UserRolesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRoles", ctx, userID)
	ret0, _ := ret[0].(*dto.UserRolesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRoles indicates an expected call of GetUserRoles.
func (mr *MockRoleUseCaseMockRecorder) GetUserRoles(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRoles", reflect.TypeOf((*MockRoleUseCase)(nil).GetUserRoles), ctx, userID)
}

// ListRoles mocks base method.
func (m *MockRoleUseCase) ListRoles(ctx context.Context) ([]dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockRoleUseCaseMockRecorder) ListRoles(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockRoleUseCase)(nil).ListRoles), ctx)
}

// RemoveRole mocks base method.
func (m *MockRoleUseCase) RemoveRole(ctx context.Context, userID, roleID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, userID, roleID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockRoleUseCaseMockRecorder) RemoveRole(ctx, userID, roleID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockRoleUseCase)(nil).RemoveRole), ctx, userID, roleID)
}

// SetPermission mocks base method.
func (m *MockRoleUseCase) SetPermission(ctx context.Context, roleID uuid.UUID, req dto.SetPermissionRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPermission", ctx, roleID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPermission indicates an expected call of SetPermission.
func (mr *MockRoleUseCaseMockRecorder) SetPermission(ctx, roleID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPermission", reflect.TypeOf((*MockRoleUseCase)(nil).SetPermission), ctx, roleID, req)
}

// UpdateRole mocks base method.
func (m *MockRoleUseCase) UpdateRole(ctx context.Context, id uuid.UUID, req dto.UpdateRoleRequest) (*dto.RoleResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateRole", ctx, id, req)
	ret0, _ := ret[0].(*dto.RoleResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateRole indicates an expected call of UpdateRole.
func (mr *MockRoleUseCaseMockRecorder) UpdateRole(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateRole", reflect.TypeOf((*MockRoleUseCase)(nil).UpdateRole), ctx, id, req)
}
