// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryUseCase is a mock of CategoryUseCase interface.
type MockCategoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryUseCaseMockRecorder
	isgomock struct{}
}

// MockCategoryUseCaseMockRecorder is the mock recorder for MockCategoryUseCase.
type MockCategoryUseCaseMockRecorder struct {
	mock *MockCategoryUseCase
}

// NewMockCategoryUseCase creates a new mock instance.
func NewMockCategoryUseCase(ctrl *gomock.Controller) *MockCategoryUseCase {
	mock := &MockCategoryUseCase{ctrl: ctrl}
	mock.recorder = &MockCategoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryUseCase) EXPECT() *MockCategoryUseCaseMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryUseCase) Create(ctx context.Context, req *dto.CreateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockCategoryUseCaseMockRecorder) Create(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryUseCase)(nil).Create), ctx, req)
}

// Delete mocks base method.
func (m *MockCategoryUseCase) Delete(ctx context.Context, id uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryUseCaseMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryUseCase)(nil).Delete), ctx, id)
}

// GetByID mocks base method.
func (m *MockCategoryUseCase) GetByID(ctx context.Context, id uuid.UUID) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryUseCaseMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryUseCase)(nil).GetByID), ctx, id)
}

// List mocks base method.
func (m *MockCategoryUseCase) List(ctx context.Context, page, pageSize int) (*repository.PaginatedResult[dto.CategoryResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.CategoryResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockCategoryUseCaseMockRecorder) List(ctx, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoryUseCase)(nil).List), ctx, page, pageSize)
}

// Update mocks base method.
func (m *MockCategoryUseCase) Update(ctx context.Context, id uuid.UUID, req *dto.UpdateCategoryRequest) (*dto.CategoryResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, req)
	ret0, _ := ret[0].(*dto.CategoryResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockCategoryUseCaseMockRecorder) Update(ctx, id, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryUseCase)(nil).Update), ctx, id, req)
}
