// Code generated by MockGen. DO NOT EDIT.
// Source: handler.go
//
// Generated by this command:
//
//	mockgen -source=handler.go -destination=mocks/mock_handler.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockPlanHandler is a mock of PlanHandler interface.
type MockPlanHandler struct {
	ctrl     *gomock.Controller
	recorder *MockPlanHandlerMockRecorder
	isgomock struct{}
}

// MockPlanHandlerMockRecorder is the mock recorder for MockPlanHandler.
type MockPlanHandlerMockRecorder struct {
	mock *MockPlanHandler
}

// NewMockPlanHandler creates a new mock instance.
func NewMockPlanHandler(ctrl *gomock.Controller) *MockPlanHandler {
	mock := &MockPlanHandler{ctrl: ctrl}
	mock.recorder = &MockPlanHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanHandler) EXPECT() *MockPlanHandlerMockRecorder {
	return m.recorder
}

// AssignTagToTier mocks base method.
func (m *MockPlanHandler) AssignTagToTier(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AssignTagToTier", c)
}

// AssignTagToTier indicates an expected call of AssignTagToTier.
func (mr *MockPlanHandlerMockRecorder) AssignTagToTier(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignTagToTier", reflect.TypeOf((*MockPlanHandler)(nil).AssignTagToTier), c)
}

// CheckBlogAccess mocks base method.
func (m *MockPlanHandler) CheckBlogAccess(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckBlogAccess", c)
}

// CheckBlogAccess indicates an expected call of CheckBlogAccess.
func (mr *MockPlanHandlerMockRecorder) CheckBlogAccess(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBlogAccess", reflect.TypeOf((*MockPlanHandler)(nil).CheckBlogAccess), c)
}

// GetAuthorPlans mocks base method.
func (m *MockPlanHandler) GetAuthorPlans(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAuthorPlans", c)
}

// GetAuthorPlans indicates an expected call of GetAuthorPlans.
func (mr *MockPlanHandlerMockRecorder) GetAuthorPlans(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPlans", reflect.TypeOf((*MockPlanHandler)(nil).GetAuthorPlans), c)
}

// GetAuthorTagTiers mocks base method.
func (m *MockPlanHandler) GetAuthorTagTiers(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetAuthorTagTiers", c)
}

// GetAuthorTagTiers indicates an expected call of GetAuthorTagTiers.
func (mr *MockPlanHandlerMockRecorder) GetAuthorTagTiers(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorTagTiers", reflect.TypeOf((*MockPlanHandler)(nil).GetAuthorTagTiers), c)
}

// UnassignTagFromTier mocks base method.
func (m *MockPlanHandler) UnassignTagFromTier(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UnassignTagFromTier", c)
}

// UnassignTagFromTier indicates an expected call of UnassignTagFromTier.
func (mr *MockPlanHandlerMockRecorder) UnassignTagFromTier(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnassignTagFromTier", reflect.TypeOf((*MockPlanHandler)(nil).UnassignTagFromTier), c)
}

// UpsertPlans mocks base method.
func (m *MockPlanHandler) UpsertPlans(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpsertPlans", c)
}

// UpsertPlans indicates an expected call of UpsertPlans.
func (mr *MockPlanHandlerMockRecorder) UpsertPlans(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPlans", reflect.TypeOf((*MockPlanHandler)(nil).UpsertPlans), c)
}
