// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockCategoryHandler is a mock of CategoryHandler interface.
type MockCategoryHandler struct {
	ctrl     *gomock.Controller
	recorder *MockCategoryHandlerMockRecorder
	isgomock struct{}
}

// MockCategoryHandlerMockRecorder is the mock recorder for MockCategoryHandler.
type MockCategoryHandlerMockRecorder struct {
	mock *MockCategoryHandler
}

// NewMockCategoryHandler creates a new mock instance.
func NewMockCategoryHandler(ctrl *gomock.Controller) *MockCategoryHandler {
	mock := &MockCategoryHandler{ctrl: ctrl}
	mock.recorder = &MockCategoryHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCategoryHandler) EXPECT() *MockCategoryHandlerMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockCategoryHandler) Create(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Create", c)
}

// Create indicates an expected call of Create.
func (mr *MockCategoryHandlerMockRecorder) Create(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockCategoryHandler)(nil).Create), c)
}

// Delete mocks base method.
func (m *MockCategoryHandler) Delete(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Delete", c)
}

// Delete indicates an expected call of Delete.
func (mr *MockCategoryHandlerMockRecorder) Delete(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockCategoryHandler)(nil).Delete), c)
}

// GetByID mocks base method.
func (m *MockCategoryHandler) GetByID(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetByID", c)
}

// GetByID indicates an expected call of GetByID.
func (mr *MockCategoryHandlerMockRecorder) GetByID(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockCategoryHandler)(nil).GetByID), c)
}

// List mocks base method.
func (m *MockCategoryHandler) List(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "List", c)
}

// List indicates an expected call of List.
func (mr *MockCategoryHandlerMockRecorder) List(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockCategoryHandler)(nil).List), c)
}

// Update mocks base method.
func (m *MockCategoryHandler) Update(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", c)
}

// Update indicates an expected call of Update.
func (mr *MockCategoryHandlerMockRecorder) Update(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockCategoryHandler)(nil).Update), c)
}
