// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockReadingHistoryUseCase is a mock of ReadingHistoryUseCase interface.
type MockReadingHistoryUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockReadingHistoryUseCaseMockRecorder
	isgomock struct{}
}

// MockReadingHistoryUseCaseMockRecorder is the mock recorder for MockReadingHistoryUseCase.
type MockReadingHistoryUseCaseMockRecorder struct {
	mock *MockReadingHistoryUseCase
}

// NewMockReadingHistoryUseCase creates a new mock instance.
func NewMockReadingHistoryUseCase(ctrl *gomock.Controller) *MockReadingHistoryUseCase {
	mock := &MockReadingHistoryUseCase{ctrl: ctrl}
	mock.recorder = &MockReadingHistoryUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadingHistoryUseCase) EXPECT() *MockReadingHistoryUseCaseMockRecorder {
	return m.recorder
}

// GetHistory mocks base method.
func (m *MockReadingHistoryUseCase) GetHistory(ctx context.Context, userID uuid.UUID, limit int) (*dto.ReadingHistoryListResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHistory", ctx, userID, limit)
	ret0, _ := ret[0].(*dto.ReadingHistoryListResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHistory indicates an expected call of GetHistory.
func (mr *MockReadingHistoryUseCaseMockRecorder) GetHistory(ctx, userID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHistory", reflect.TypeOf((*MockReadingHistoryUseCase)(nil).GetHistory), ctx, userID, limit)
}

// MarkAsRead mocks base method.
func (m *MockReadingHistoryUseCase) MarkAsRead(ctx context.Context, userID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, userID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockReadingHistoryUseCaseMockRecorder) MarkAsRead(ctx, userID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockReadingHistoryUseCase)(nil).MarkAsRead), ctx, userID, blogID)
}
