// Code generated by MockGen. DO NOT EDIT.
// Source: definition.go
//
// Generated by this command:
//
//	mockgen -source=definition.go -destination=mocks/mock_definition.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gin "github.com/gin-gonic/gin"
	gomock "go.uber.org/mock/gomock"
)

// MockSubscriptionHandler is a mock of SubscriptionHandler interface.
type MockSubscriptionHandler struct {
	ctrl     *gomock.Controller
	recorder *MockSubscriptionHandlerMockRecorder
	isgomock struct{}
}

// MockSubscriptionHandlerMockRecorder is the mock recorder for MockSubscriptionHandler.
type MockSubscriptionHandlerMockRecorder struct {
	mock *MockSubscriptionHandler
}

// NewMockSubscriptionHandler creates a new mock instance.
func NewMockSubscriptionHandler(ctrl *gomock.Controller) *MockSubscriptionHandler {
	mock := &MockSubscriptionHandler{ctrl: ctrl}
	mock.recorder = &MockSubscriptionHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSubscriptionHandler) EXPECT() *MockSubscriptionHandlerMockRecorder {
	return m.recorder
}

// CheckSubscriptionStatus mocks base method.
func (m *MockSubscriptionHandler) CheckSubscriptionStatus(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CheckSubscriptionStatus", c)
}

// CheckSubscriptionStatus indicates an expected call of CheckSubscriptionStatus.
func (mr *MockSubscriptionHandlerMockRecorder) CheckSubscriptionStatus(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckSubscriptionStatus", reflect.TypeOf((*MockSubscriptionHandler)(nil).CheckSubscriptionStatus), c)
}

// CountSubscribers mocks base method.
func (m *MockSubscriptionHandler) CountSubscribers(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "CountSubscribers", c)
}

// CountSubscribers indicates an expected call of CountSubscribers.
func (mr *MockSubscriptionHandlerMockRecorder) CountSubscribers(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CountSubscribers", reflect.TypeOf((*MockSubscriptionHandler)(nil).CountSubscribers), c)
}

// GetMySubscriptions mocks base method.
func (m *MockSubscriptionHandler) GetMySubscriptions(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetMySubscriptions", c)
}

// GetMySubscriptions indicates an expected call of GetMySubscriptions.
func (mr *MockSubscriptionHandlerMockRecorder) GetMySubscriptions(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMySubscriptions", reflect.TypeOf((*MockSubscriptionHandler)(nil).GetMySubscriptions), c)
}

// GetSubscribers mocks base method.
func (m *MockSubscriptionHandler) GetSubscribers(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSubscribers", c)
}

// GetSubscribers indicates an expected call of GetSubscribers.
func (mr *MockSubscriptionHandlerMockRecorder) GetSubscribers(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscribers", reflect.TypeOf((*MockSubscriptionHandler)(nil).GetSubscribers), c)
}

// GetSubscriptionCounts mocks base method.
func (m *MockSubscriptionHandler) GetSubscriptionCounts(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetSubscriptionCounts", c)
}

// GetSubscriptionCounts indicates an expected call of GetSubscriptionCounts.
func (mr *MockSubscriptionHandlerMockRecorder) GetSubscriptionCounts(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSubscriptionCounts", reflect.TypeOf((*MockSubscriptionHandler)(nil).GetSubscriptionCounts), c)
}

// GetUserSubscriptions mocks base method.
func (m *MockSubscriptionHandler) GetUserSubscriptions(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "GetUserSubscriptions", c)
}

// GetUserSubscriptions indicates an expected call of GetUserSubscriptions.
func (mr *MockSubscriptionHandlerMockRecorder) GetUserSubscriptions(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserSubscriptions", reflect.TypeOf((*MockSubscriptionHandler)(nil).GetUserSubscriptions), c)
}

// Subscribe mocks base method.
func (m *MockSubscriptionHandler) Subscribe(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Subscribe", c)
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockSubscriptionHandlerMockRecorder) Subscribe(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockSubscriptionHandler)(nil).Subscribe), c)
}

// Unsubscribe mocks base method.
func (m *MockSubscriptionHandler) Unsubscribe(c *gin.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Unsubscribe", c)
}

// Unsubscribe indicates an expected call of Unsubscribe.
func (mr *MockSubscriptionHandlerMockRecorder) Unsubscribe(c any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unsubscribe", reflect.TypeOf((*MockSubscriptionHandler)(nil).Unsubscribe), c)
}
