// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source=usecase.go -destination=mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockSeriesUseCase is a mock of SeriesUseCase interface.
type MockSeriesUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockSeriesUseCaseMockRecorder
	isgomock struct{}
}

// MockSeriesUseCaseMockRecorder is the mock recorder for MockSeriesUseCase.
type MockSeriesUseCaseMockRecorder struct {
	mock *MockSeriesUseCase
}

// NewMockSeriesUseCase creates a new mock instance.
func NewMockSeriesUseCase(ctrl *gomock.Controller) *MockSeriesUseCase {
	mock := &MockSeriesUseCase{ctrl: ctrl}
	mock.recorder = &MockSeriesUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSeriesUseCase) EXPECT() *MockSeriesUseCaseMockRecorder {
	return m.recorder
}

// AddBlogToSeries mocks base method.
func (m *MockSeriesUseCase) AddBlogToSeries(ctx context.Context, userID, seriesID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddBlogToSeries", ctx, userID, seriesID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddBlogToSeries indicates an expected call of AddBlogToSeries.
func (mr *MockSeriesUseCaseMockRecorder) AddBlogToSeries(ctx, userID, seriesID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddBlogToSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).AddBlogToSeries), ctx, userID, seriesID, blogID)
}

// CreateSeries mocks base method.
func (m *MockSeriesUseCase) CreateSeries(ctx context.Context, userID uuid.UUID, req *dto.CreateSeriesRequest) (*dto.SeriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateSeries", ctx, userID, req)
	ret0, _ := ret[0].(*dto.SeriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateSeries indicates an expected call of CreateSeries.
func (mr *MockSeriesUseCaseMockRecorder) CreateSeries(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).CreateSeries), ctx, userID, req)
}

// DeleteSeries mocks base method.
func (m *MockSeriesUseCase) DeleteSeries(ctx context.Context, userID, seriesID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteSeries", ctx, userID, seriesID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteSeries indicates an expected call of DeleteSeries.
func (mr *MockSeriesUseCaseMockRecorder) DeleteSeries(ctx, userID, seriesID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).DeleteSeries), ctx, userID, seriesID)
}

// GetHighlightedSeries mocks base method.
func (m *MockSeriesUseCase) GetHighlightedSeries(ctx context.Context) ([]*dto.HighlightedSeriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHighlightedSeries", ctx)
	ret0, _ := ret[0].([]*dto.HighlightedSeriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetHighlightedSeries indicates an expected call of GetHighlightedSeries.
func (mr *MockSeriesUseCaseMockRecorder) GetHighlightedSeries(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHighlightedSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).GetHighlightedSeries), ctx)
}

// GetSeriesByID mocks base method.
func (m *MockSeriesUseCase) GetSeriesByID(ctx context.Context, id uuid.UUID) (*dto.SeriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeriesByID", ctx, id)
	ret0, _ := ret[0].(*dto.SeriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesByID indicates an expected call of GetSeriesByID.
func (mr *MockSeriesUseCaseMockRecorder) GetSeriesByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesByID", reflect.TypeOf((*MockSeriesUseCase)(nil).GetSeriesByID), ctx, id)
}

// GetSeriesBySlug mocks base method.
func (m *MockSeriesUseCase) GetSeriesBySlug(ctx context.Context, slug string) (*dto.SeriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetSeriesBySlug", ctx, slug)
	ret0, _ := ret[0].(*dto.SeriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetSeriesBySlug indicates an expected call of GetSeriesBySlug.
func (mr *MockSeriesUseCaseMockRecorder) GetSeriesBySlug(ctx, slug any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetSeriesBySlug", reflect.TypeOf((*MockSeriesUseCase)(nil).GetSeriesBySlug), ctx, slug)
}

// ListSeries mocks base method.
func (m *MockSeriesUseCase) ListSeries(ctx context.Context, params *dto.SeriesFilterParams) ([]dto.SeriesResponse, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListSeries", ctx, params)
	ret0, _ := ret[0].([]dto.SeriesResponse)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListSeries indicates an expected call of ListSeries.
func (mr *MockSeriesUseCaseMockRecorder) ListSeries(ctx, params any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).ListSeries), ctx, params)
}

// RemoveBlogFromSeries mocks base method.
func (m *MockSeriesUseCase) RemoveBlogFromSeries(ctx context.Context, userID, seriesID, blogID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveBlogFromSeries", ctx, userID, seriesID, blogID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveBlogFromSeries indicates an expected call of RemoveBlogFromSeries.
func (mr *MockSeriesUseCaseMockRecorder) RemoveBlogFromSeries(ctx, userID, seriesID, blogID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveBlogFromSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).RemoveBlogFromSeries), ctx, userID, seriesID, blogID)
}

// UpdateSeries mocks base method.
func (m *MockSeriesUseCase) UpdateSeries(ctx context.Context, userID, seriesID uuid.UUID, req *dto.UpdateSeriesRequest) (*dto.SeriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSeries", ctx, userID, seriesID, req)
	ret0, _ := ret[0].(*dto.SeriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateSeries indicates an expected call of UpdateSeries.
func (mr *MockSeriesUseCaseMockRecorder) UpdateSeries(ctx, userID, seriesID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSeries", reflect.TypeOf((*MockSeriesUseCase)(nil).UpdateSeries), ctx, userID, seriesID, req)
}
