// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/adapter/sepay_adapter.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/adapter/sepay_adapter.go -destination=internal/infrastructure/adapter/mocks/mock_sepay_adapter.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	adapter "github.com/aiagent/internal/infrastructure/adapter"
	gomock "go.uber.org/mock/gomock"
)

// MockSePayAdapter is a mock of SePayAdapter interface.
type MockSePayAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockSePayAdapterMockRecorder
	isgomock struct{}
}

// MockSePayAdapterMockRecorder is the mock recorder for MockSePayAdapter.
type MockSePayAdapterMockRecorder struct {
	mock *MockSePayAdapter
}

// NewMockSePayAdapter creates a new mock instance.
func NewMockSePayAdapter(ctrl *gomock.Controller) *MockSePayAdapter {
	mock := &MockSePayAdapter{ctrl: ctrl}
	mock.recorder = &MockSePayAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSePayAdapter) EXPECT() *MockSePayAdapterMockRecorder {
	return m.recorder
}

// CreateVietQR mocks base method.
func (m *MockSePayAdapter) CreateVietQR(ctx context.Context, req adapter.CreateVietQRRequest) (*adapter.VietQRResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVietQR", ctx, req)
	ret0, _ := ret[0].(*adapter.VietQRResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVietQR indicates an expected call of CreateVietQR.
func (mr *MockSePayAdapterMockRecorder) CreateVietQR(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVietQR", reflect.TypeOf((*MockSePayAdapter)(nil).CreateVietQR), ctx, req)
}

// GetBankTransferInfo mocks base method.
func (m *MockSePayAdapter) GetBankTransferInfo() adapter.BankTransferInfo {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBankTransferInfo")
	ret0, _ := ret[0].(adapter.BankTransferInfo)
	return ret0
}

// GetBankTransferInfo indicates an expected call of GetBankTransferInfo.
func (mr *MockSePayAdapterMockRecorder) GetBankTransferInfo() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBankTransferInfo", reflect.TypeOf((*MockSePayAdapter)(nil).GetBankTransferInfo))
}

// GetTransactionBySePayID mocks base method.
func (m *MockSePayAdapter) GetTransactionBySePayID(ctx context.Context, sepayID string) (*adapter.SePayTransaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionBySePayID", ctx, sepayID)
	ret0, _ := ret[0].(*adapter.SePayTransaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionBySePayID indicates an expected call of GetTransactionBySePayID.
func (mr *MockSePayAdapterMockRecorder) GetTransactionBySePayID(ctx, sepayID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionBySePayID", reflect.TypeOf((*MockSePayAdapter)(nil).GetTransactionBySePayID), ctx, sepayID)
}

// VerifyWebhookSignature mocks base method.
func (m *MockSePayAdapter) VerifyWebhookSignature(payload map[string]any, signature string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifyWebhookSignature", payload, signature)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifyWebhookSignature indicates an expected call of VerifyWebhookSignature.
func (mr *MockSePayAdapterMockRecorder) VerifyWebhookSignature(payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifyWebhookSignature", reflect.TypeOf((*MockSePayAdapter)(nil).VerifyWebhookSignature), payload, signature)
}
