// Code generated by MockGen. DO NOT EDIT.
// Source: internal/infrastructure/adapter/smtp_adapter.go
//
// Generated by this command:
//
//	mockgen -source=internal/infrastructure/adapter/smtp_adapter.go -destination=internal/infrastructure/adapter/mocks/mock_email_provider.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockEmailProvider is a mock of EmailProvider interface.
type MockEmailProvider struct {
	ctrl     *gomock.Controller
	recorder *MockEmailProviderMockRecorder
	isgomock struct{}
}

// MockEmailProviderMockRecorder is the mock recorder for MockEmailProvider.
type MockEmailProviderMockRecorder struct {
	mock *MockEmailProvider
}

// NewMockEmailProvider creates a new mock instance.
func NewMockEmailProvider(ctrl *gomock.Controller) *MockEmailProvider {
	mock := &MockEmailProvider{ctrl: ctrl}
	mock.recorder = &MockEmailProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailProvider) EXPECT() *MockEmailProviderMockRecorder {
	return m.recorder
}

// Send mocks base method.
func (m *MockEmailProvider) Send(ctx context.Context, to []string, subject, htmlBody, textBody string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Send", ctx, to, subject, htmlBody, textBody)
	ret0, _ := ret[0].(error)
	return ret0
}

// Send indicates an expected call of Send.
func (mr *MockEmailProviderMockRecorder) Send(ctx, to, subject, htmlBody, textBody any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Send", reflect.TypeOf((*MockEmailProvider)(nil).Send), ctx, to, subject, htmlBody, textBody)
}
