// Code generated by MockGen. DO NOT EDIT.
// Source: recommendation_service.go
//
// Generated by this command:
//
//	mockgen -source=recommendation_service.go -destination=mocks/mock_recommendation_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRecommendationService is a mock of RecommendationService interface.
type MockRecommendationService struct {
	ctrl     *gomock.Controller
	recorder *MockRecommendationServiceMockRecorder
	isgomock struct{}
}

// MockRecommendationServiceMockRecorder is the mock recorder for MockRecommendationService.
type MockRecommendationServiceMockRecorder struct {
	mock *MockRecommendationService
}

// NewMockRecommendationService creates a new mock instance.
func NewMockRecommendationService(ctrl *gomock.Controller) *MockRecommendationService {
	mock := &MockRecommendationService{ctrl: ctrl}
	mock.recorder = &MockRecommendationServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRecommendationService) EXPECT() *MockRecommendationServiceMockRecorder {
	return m.recorder
}

// GetPersonalizedFeed mocks base method.
func (m *MockRecommendationService) GetPersonalizedFeed(ctx context.Context, userID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.Blog], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPersonalizedFeed", ctx, userID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.Blog])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPersonalizedFeed indicates an expected call of GetPersonalizedFeed.
func (mr *MockRecommendationServiceMockRecorder) GetPersonalizedFeed(ctx, userID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPersonalizedFeed", reflect.TypeOf((*MockRecommendationService)(nil).GetPersonalizedFeed), ctx, userID, pagination)
}

// GetPopularTags mocks base method.
func (m *MockRecommendationService) GetPopularTags(ctx context.Context, limit int) ([]entity.Tag, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPopularTags", ctx, limit)
	ret0, _ := ret[0].([]entity.Tag)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPopularTags indicates an expected call of GetPopularTags.
func (mr *MockRecommendationServiceMockRecorder) GetPopularTags(ctx, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPopularTags", reflect.TypeOf((*MockRecommendationService)(nil).GetPopularTags), ctx, limit)
}

// GetRelatedBlogs mocks base method.
func (m *MockRecommendationService) GetRelatedBlogs(ctx context.Context, blogID uuid.UUID, limit int) ([]entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelatedBlogs", ctx, blogID, limit)
	ret0, _ := ret[0].([]entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelatedBlogs indicates an expected call of GetRelatedBlogs.
func (mr *MockRecommendationServiceMockRecorder) GetRelatedBlogs(ctx, blogID, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelatedBlogs", reflect.TypeOf((*MockRecommendationService)(nil).GetRelatedBlogs), ctx, blogID, limit)
}

// UpdateInterests mocks base method.
func (m *MockRecommendationService) UpdateInterests(ctx context.Context, userID uuid.UUID, tagIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateInterests", ctx, userID, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateInterests indicates an expected call of UpdateInterests.
func (mr *MockRecommendationServiceMockRecorder) UpdateInterests(ctx, userID, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateInterests", reflect.TypeOf((*MockRecommendationService)(nil).UpdateInterests), ctx, userID, tagIDs)
}
