// Code generated by MockGen. DO NOT EDIT.
// Source: system_service.go
//
// Generated by this command:
//
//	mockgen -source=system_service.go -destination=mocks/mock_system_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/aiagent/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSystemService is a mock of SystemService interface.
type MockSystemService struct {
	ctrl     *gomock.Controller
	recorder *MockSystemServiceMockRecorder
	isgomock struct{}
}

// MockSystemServiceMockRecorder is the mock recorder for MockSystemService.
type MockSystemServiceMockRecorder struct {
	mock *MockSystemService
}

// NewMockSystemService creates a new mock instance.
func NewMockSystemService(ctrl *gomock.Controller) *MockSystemService {
	mock := &MockSystemService{ctrl: ctrl}
	mock.recorder = &MockSystemServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSystemService) EXPECT() *MockSystemServiceMockRecorder {
	return m.recorder
}

// CheckHealth mocks base method.
func (m *MockSystemService) CheckHealth(ctx context.Context) (service.SystemStatus, map[string]bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckHealth", ctx)
	ret0, _ := ret[0].(service.SystemStatus)
	ret1, _ := ret[1].(map[string]bool)
	return ret0, ret1
}

// CheckHealth indicates an expected call of CheckHealth.
func (mr *MockSystemServiceMockRecorder) CheckHealth(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckHealth", reflect.TypeOf((*MockSystemService)(nil).CheckHealth), ctx)
}
