// Code generated by MockGen. DO NOT EDIT.
// Source: version_service.go
//
// Generated by this command:
//
//	mockgen -source=version_service.go -destination=mocks/mock_version_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockVersionService is a mock of VersionService interface.
type MockVersionService struct {
	ctrl     *gomock.Controller
	recorder *MockVersionServiceMockRecorder
	isgomock struct{}
}

// MockVersionServiceMockRecorder is the mock recorder for MockVersionService.
type MockVersionServiceMockRecorder struct {
	mock *MockVersionService
}

// NewMockVersionService creates a new mock instance.
func NewMockVersionService(ctrl *gomock.Controller) *MockVersionService {
	mock := &MockVersionService{ctrl: ctrl}
	mock.recorder = &MockVersionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockVersionService) EXPECT() *MockVersionServiceMockRecorder {
	return m.recorder
}

// CreateVersion mocks base method.
func (m *MockVersionService) CreateVersion(ctx context.Context, blog *entity.Blog, editorID uuid.UUID, changeSummary string) (*entity.BlogVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateVersion", ctx, blog, editorID, changeSummary)
	ret0, _ := ret[0].(*entity.BlogVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateVersion indicates an expected call of CreateVersion.
func (mr *MockVersionServiceMockRecorder) CreateVersion(ctx, blog, editorID, changeSummary any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateVersion", reflect.TypeOf((*MockVersionService)(nil).CreateVersion), ctx, blog, editorID, changeSummary)
}

// DeleteVersion mocks base method.
func (m *MockVersionService) DeleteVersion(ctx context.Context, versionID, requesterID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteVersion", ctx, versionID, requesterID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteVersion indicates an expected call of DeleteVersion.
func (mr *MockVersionServiceMockRecorder) DeleteVersion(ctx, versionID, requesterID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteVersion", reflect.TypeOf((*MockVersionService)(nil).DeleteVersion), ctx, versionID, requesterID)
}

// GetVersion mocks base method.
func (m *MockVersionService) GetVersion(ctx context.Context, versionID uuid.UUID) (*entity.BlogVersion, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVersion", ctx, versionID)
	ret0, _ := ret[0].(*entity.BlogVersion)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVersion indicates an expected call of GetVersion.
func (mr *MockVersionServiceMockRecorder) GetVersion(ctx, versionID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVersion", reflect.TypeOf((*MockVersionService)(nil).GetVersion), ctx, versionID)
}

// ListVersions mocks base method.
func (m *MockVersionService) ListVersions(ctx context.Context, blogID uuid.UUID, pagination repository.Pagination) (*repository.PaginatedResult[entity.BlogVersion], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListVersions", ctx, blogID, pagination)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.BlogVersion])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListVersions indicates an expected call of ListVersions.
func (mr *MockVersionServiceMockRecorder) ListVersions(ctx, blogID, pagination any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListVersions", reflect.TypeOf((*MockVersionService)(nil).ListVersions), ctx, blogID, pagination)
}

// RestoreVersion mocks base method.
func (m *MockVersionService) RestoreVersion(ctx context.Context, blogID, versionID, editorID uuid.UUID) (*entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RestoreVersion", ctx, blogID, versionID, editorID)
	ret0, _ := ret[0].(*entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RestoreVersion indicates an expected call of RestoreVersion.
func (mr *MockVersionServiceMockRecorder) RestoreVersion(ctx, blogID, versionID, editorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RestoreVersion", reflect.TypeOf((*MockVersionService)(nil).RestoreVersion), ctx, blogID, versionID, editorID)
}
