// Code generated by MockGen. DO NOT EDIT.
// Source: content_access_service.go
//
// Generated by this command:
//
//	mockgen -source=content_access_service.go -destination=mocks/mock_content_access_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	service "github.com/aiagent/internal/domain/service"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockContentAccessService is a mock of ContentAccessService interface.
type MockContentAccessService struct {
	ctrl     *gomock.Controller
	recorder *MockContentAccessServiceMockRecorder
	isgomock struct{}
}

// MockContentAccessServiceMockRecorder is the mock recorder for MockContentAccessService.
type MockContentAccessServiceMockRecorder struct {
	mock *MockContentAccessService
}

// NewMockContentAccessService creates a new mock instance.
func NewMockContentAccessService(ctrl *gomock.Controller) *MockContentAccessService {
	mock := &MockContentAccessService{ctrl: ctrl}
	mock.recorder = &MockContentAccessServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockContentAccessService) EXPECT() *MockContentAccessServiceMockRecorder {
	return m.recorder
}

// CheckBlogAccess mocks base method.
func (m *MockContentAccessService) CheckBlogAccess(ctx context.Context, blogID uuid.UUID, userID *uuid.UUID) (*service.AccessResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckBlogAccess", ctx, blogID, userID)
	ret0, _ := ret[0].(*service.AccessResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckBlogAccess indicates an expected call of CheckBlogAccess.
func (mr *MockContentAccessServiceMockRecorder) CheckBlogAccess(ctx, blogID, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckBlogAccess", reflect.TypeOf((*MockContentAccessService)(nil).CheckBlogAccess), ctx, blogID, userID)
}

// GetUserTier mocks base method.
func (m *MockContentAccessService) GetUserTier(ctx context.Context, userID, authorID uuid.UUID) (entity.SubscriptionTier, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTier", ctx, userID, authorID)
	ret0, _ := ret[0].(entity.SubscriptionTier)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTier indicates an expected call of GetUserTier.
func (mr *MockContentAccessServiceMockRecorder) GetUserTier(ctx, userID, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTier", reflect.TypeOf((*MockContentAccessService)(nil).GetUserTier), ctx, userID, authorID)
}
