// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/task_runner.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/task_runner.go -destination=internal/domain/service/mocks/mock_task_runner.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockTaskRunner is a mock of TaskRunner interface.
type MockTaskRunner struct {
	ctrl     *gomock.Controller
	recorder *MockTaskRunnerMockRecorder
	isgomock struct{}
}

// MockTaskRunnerMockRecorder is the mock recorder for MockTaskRunner.
type MockTaskRunnerMockRecorder struct {
	mock *MockTaskRunner
}

// NewMockTaskRunner creates a new mock instance.
func NewMockTaskRunner(ctrl *gomock.Controller) *MockTaskRunner {
	mock := &MockTaskRunner{ctrl: ctrl}
	mock.recorder = &MockTaskRunnerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTaskRunner) EXPECT() *MockTaskRunnerMockRecorder {
	return m.recorder
}

// Submit mocks base method.
func (m *MockTaskRunner) Submit(task func(context.Context)) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Submit", task)
}

// Submit indicates an expected call of Submit.
func (mr *MockTaskRunnerMockRecorder) Submit(task any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Submit", reflect.TypeOf((*MockTaskRunner)(nil).Submit), task)
}
