// Code generated by MockGen. DO NOT EDIT.
// Source: permission_service.go
//
// Generated by this command:
//
//	mockgen -source=permission_service.go -destination=mocks/mock_permission_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPermissionService is a mock of PermissionService interface.
type MockPermissionService struct {
	ctrl     *gomock.Controller
	recorder *MockPermissionServiceMockRecorder
	isgomock struct{}
}

// MockPermissionServiceMockRecorder is the mock recorder for MockPermissionService.
type MockPermissionServiceMockRecorder struct {
	mock *MockPermissionService
}

// NewMockPermissionService creates a new mock instance.
func NewMockPermissionService(ctrl *gomock.Controller) *MockPermissionService {
	mock := &MockPermissionService{ctrl: ctrl}
	mock.recorder = &MockPermissionServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPermissionService) EXPECT() *MockPermissionServiceMockRecorder {
	return m.recorder
}

// CheckPermission mocks base method.
func (m *MockPermissionService) CheckPermission(ctx context.Context, userID uuid.UUID, resource string, permission entity.Permission) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckPermission", ctx, userID, resource, permission)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CheckPermission indicates an expected call of CheckPermission.
func (mr *MockPermissionServiceMockRecorder) CheckPermission(ctx, userID, resource, permission any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckPermission", reflect.TypeOf((*MockPermissionService)(nil).CheckPermission), ctx, userID, resource, permission)
}

// CombinePermissions mocks base method.
func (m *MockPermissionService) CombinePermissions(permissions ...entity.Permission) entity.Permission {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range permissions {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "CombinePermissions", varargs...)
	ret0, _ := ret[0].(entity.Permission)
	return ret0
}

// CombinePermissions indicates an expected call of CombinePermissions.
func (mr *MockPermissionServiceMockRecorder) CombinePermissions(permissions ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CombinePermissions", reflect.TypeOf((*MockPermissionService)(nil).CombinePermissions), permissions...)
}

// GetUserPermission mocks base method.
func (m *MockPermissionService) GetUserPermission(ctx context.Context, userID uuid.UUID, resource string) (entity.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserPermission", ctx, userID, resource)
	ret0, _ := ret[0].(entity.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserPermission indicates an expected call of GetUserPermission.
func (mr *MockPermissionServiceMockRecorder) GetUserPermission(ctx, userID, resource any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserPermission", reflect.TypeOf((*MockPermissionService)(nil).GetUserPermission), ctx, userID, resource)
}

// HasPermission mocks base method.
func (m *MockPermissionService) HasPermission(permission, required entity.Permission) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HasPermission", permission, required)
	ret0, _ := ret[0].(bool)
	return ret0
}

// HasPermission indicates an expected call of HasPermission.
func (mr *MockPermissionServiceMockRecorder) HasPermission(permission, required any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HasPermission", reflect.TypeOf((*MockPermissionService)(nil).HasPermission), permission, required)
}
