// Code generated by MockGen. DO NOT EDIT.
// Source: social_auth_service.go
//
// Generated by this command:
//
//	mockgen -source=social_auth_service.go -destination=mocks/mock_social_auth_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	service "github.com/aiagent/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockSocialAuthService is a mock of SocialAuthService interface.
type MockSocialAuthService struct {
	ctrl     *gomock.Controller
	recorder *MockSocialAuthServiceMockRecorder
	isgomock struct{}
}

// MockSocialAuthServiceMockRecorder is the mock recorder for MockSocialAuthService.
type MockSocialAuthServiceMockRecorder struct {
	mock *MockSocialAuthService
}

// NewMockSocialAuthService creates a new mock instance.
func NewMockSocialAuthService(ctrl *gomock.Controller) *MockSocialAuthService {
	mock := &MockSocialAuthService{ctrl: ctrl}
	mock.recorder = &MockSocialAuthServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSocialAuthService) EXPECT() *MockSocialAuthServiceMockRecorder {
	return m.recorder
}

// GetAuthURL mocks base method.
func (m *MockSocialAuthService) GetAuthURL(ctx context.Context, provider string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthURL", ctx, provider)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthURL indicates an expected call of GetAuthURL.
func (mr *MockSocialAuthServiceMockRecorder) GetAuthURL(ctx, provider any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthURL", reflect.TypeOf((*MockSocialAuthService)(nil).GetAuthURL), ctx, provider)
}

// GetUserInfo mocks base method.
func (m *MockSocialAuthService) GetUserInfo(ctx context.Context, provider, code string) (*service.SocialUserInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserInfo", ctx, provider, code)
	ret0, _ := ret[0].(*service.SocialUserInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserInfo indicates an expected call of GetUserInfo.
func (mr *MockSocialAuthServiceMockRecorder) GetUserInfo(ctx, provider, code any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserInfo", reflect.TypeOf((*MockSocialAuthService)(nil).GetUserInfo), ctx, provider, code)
}
