// Code generated by MockGen. DO NOT EDIT.
// Source: payment_service.go
//
// Generated by this command:
//
//	mockgen -source=payment_service.go -destination=mocks/mock_payment_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	service "github.com/aiagent/internal/domain/service"
	gomock "go.uber.org/mock/gomock"
)

// MockPaymentService is a mock of PaymentService interface.
type MockPaymentService struct {
	ctrl     *gomock.Controller
	recorder *MockPaymentServiceMockRecorder
	isgomock struct{}
}

// MockPaymentServiceMockRecorder is the mock recorder for MockPaymentService.
type MockPaymentServiceMockRecorder struct {
	mock *MockPaymentService
}

// NewMockPaymentService creates a new mock instance.
func NewMockPaymentService(ctrl *gomock.Controller) *MockPaymentService {
	mock := &MockPaymentService{ctrl: ctrl}
	mock.recorder = &MockPaymentServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPaymentService) EXPECT() *MockPaymentServiceMockRecorder {
	return m.recorder
}

// GetTransactionStatus mocks base method.
func (m *MockPaymentService) GetTransactionStatus(ctx context.Context, orderID string) (*entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTransactionStatus", ctx, orderID)
	ret0, _ := ret[0].(*entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTransactionStatus indicates an expected call of GetTransactionStatus.
func (mr *MockPaymentServiceMockRecorder) GetTransactionStatus(ctx, orderID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTransactionStatus", reflect.TypeOf((*MockPaymentService)(nil).GetTransactionStatus), ctx, orderID)
}

// HandleSePayWebhook mocks base method.
func (m *MockPaymentService) HandleSePayWebhook(ctx context.Context, payload service.SePayWebhookPayload) (*entity.Transaction, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HandleSePayWebhook", ctx, payload)
	ret0, _ := ret[0].(*entity.Transaction)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// HandleSePayWebhook indicates an expected call of HandleSePayWebhook.
func (mr *MockPaymentServiceMockRecorder) HandleSePayWebhook(ctx, payload any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HandleSePayWebhook", reflect.TypeOf((*MockPaymentService)(nil).HandleSePayWebhook), ctx, payload)
}

// InitPayment mocks base method.
func (m *MockPaymentService) InitPayment(ctx context.Context, req service.CreatePaymentRequest) (*service.PaymentResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "InitPayment", ctx, req)
	ret0, _ := ret[0].(*service.PaymentResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// InitPayment indicates an expected call of InitPayment.
func (mr *MockPaymentServiceMockRecorder) InitPayment(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "InitPayment", reflect.TypeOf((*MockPaymentService)(nil).InitPayment), ctx, req)
}

// VerifySePayWebhookSignature mocks base method.
func (m *MockPaymentService) VerifySePayWebhookSignature(payload map[string]any, signature string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "VerifySePayWebhookSignature", payload, signature)
	ret0, _ := ret[0].(bool)
	return ret0
}

// VerifySePayWebhookSignature indicates an expected call of VerifySePayWebhookSignature.
func (mr *MockPaymentServiceMockRecorder) VerifySePayWebhookSignature(payload, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "VerifySePayWebhookSignature", reflect.TypeOf((*MockPaymentService)(nil).VerifySePayWebhookSignature), payload, signature)
}
