// Code generated by MockGen. DO NOT EDIT.
// Source: plan_management_service.go
//
// Generated by this command:
//
//	mockgen -source=plan_management_service.go -destination=mocks/mock_plan_management_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	service "github.com/aiagent/internal/domain/service"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockPlanManagementService is a mock of PlanManagementService interface.
type MockPlanManagementService struct {
	ctrl     *gomock.Controller
	recorder *MockPlanManagementServiceMockRecorder
	isgomock struct{}
}

// MockPlanManagementServiceMockRecorder is the mock recorder for MockPlanManagementService.
type MockPlanManagementServiceMockRecorder struct {
	mock *MockPlanManagementService
}

// NewMockPlanManagementService creates a new mock instance.
func NewMockPlanManagementService(ctrl *gomock.Controller) *MockPlanManagementService {
	mock := &MockPlanManagementService{ctrl: ctrl}
	mock.recorder = &MockPlanManagementServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPlanManagementService) EXPECT() *MockPlanManagementServiceMockRecorder {
	return m.recorder
}

// ActivatePlan mocks base method.
func (m *MockPlanManagementService) ActivatePlan(ctx context.Context, authorID uuid.UUID, tier entity.SubscriptionTier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ActivatePlan", ctx, authorID, tier)
	ret0, _ := ret[0].(error)
	return ret0
}

// ActivatePlan indicates an expected call of ActivatePlan.
func (mr *MockPlanManagementServiceMockRecorder) ActivatePlan(ctx, authorID, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ActivatePlan", reflect.TypeOf((*MockPlanManagementService)(nil).ActivatePlan), ctx, authorID, tier)
}

// DeactivatePlan mocks base method.
func (m *MockPlanManagementService) DeactivatePlan(ctx context.Context, authorID uuid.UUID, tier entity.SubscriptionTier) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivatePlan", ctx, authorID, tier)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivatePlan indicates an expected call of DeactivatePlan.
func (mr *MockPlanManagementServiceMockRecorder) DeactivatePlan(ctx, authorID, tier any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivatePlan", reflect.TypeOf((*MockPlanManagementService)(nil).DeactivatePlan), ctx, authorID, tier)
}

// GetAuthorPlans mocks base method.
func (m *MockPlanManagementService) GetAuthorPlans(ctx context.Context, authorID uuid.UUID) ([]service.PlanWithTags, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAuthorPlans", ctx, authorID)
	ret0, _ := ret[0].([]service.PlanWithTags)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAuthorPlans indicates an expected call of GetAuthorPlans.
func (mr *MockPlanManagementServiceMockRecorder) GetAuthorPlans(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAuthorPlans", reflect.TypeOf((*MockPlanManagementService)(nil).GetAuthorPlans), ctx, authorID)
}

// UpsertPlans mocks base method.
func (m *MockPlanManagementService) UpsertPlans(ctx context.Context, authorID uuid.UUID, plans []service.CreatePlanDTO) ([]entity.SubscriptionPlan, []string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertPlans", ctx, authorID, plans)
	ret0, _ := ret[0].([]entity.SubscriptionPlan)
	ret1, _ := ret[1].([]string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertPlans indicates an expected call of UpsertPlans.
func (mr *MockPlanManagementServiceMockRecorder) UpsertPlans(ctx, authorID, plans any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertPlans", reflect.TypeOf((*MockPlanManagementService)(nil).UpsertPlans), ctx, authorID, plans)
}
