// Code generated by MockGen. DO NOT EDIT.
// Source: ranking_service.go
//
// Generated by this command:
//
//	mockgen -source=ranking_service.go -destination=mocks/mock_ranking_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	service "github.com/aiagent/internal/domain/service"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockRankingService is a mock of RankingService interface.
type MockRankingService struct {
	ctrl     *gomock.Controller
	recorder *MockRankingServiceMockRecorder
	isgomock struct{}
}

// MockRankingServiceMockRecorder is the mock recorder for MockRankingService.
type MockRankingServiceMockRecorder struct {
	mock *MockRankingService
}

// NewMockRankingService creates a new mock instance.
func NewMockRankingService(ctrl *gomock.Controller) *MockRankingService {
	mock := &MockRankingService{ctrl: ctrl}
	mock.recorder = &MockRankingServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRankingService) EXPECT() *MockRankingServiceMockRecorder {
	return m.recorder
}

// ArchiveRankings mocks base method.
func (m *MockRankingService) ArchiveRankings(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ArchiveRankings", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// ArchiveRankings indicates an expected call of ArchiveRankings.
func (mr *MockRankingServiceMockRecorder) ArchiveRankings(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ArchiveRankings", reflect.TypeOf((*MockRankingService)(nil).ArchiveRankings), ctx)
}

// AssignRankPositions mocks base method.
func (m *MockRankingService) AssignRankPositions(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AssignRankPositions", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// AssignRankPositions indicates an expected call of AssignRankPositions.
func (mr *MockRankingServiceMockRecorder) AssignRankPositions(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AssignRankPositions", reflect.TypeOf((*MockRankingService)(nil).AssignRankPositions), ctx)
}

// CalculateAllVelocityScores mocks base method.
func (m *MockRankingService) CalculateAllVelocityScores(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateAllVelocityScores", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// CalculateAllVelocityScores indicates an expected call of CalculateAllVelocityScores.
func (mr *MockRankingServiceMockRecorder) CalculateAllVelocityScores(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateAllVelocityScores", reflect.TypeOf((*MockRankingService)(nil).CalculateAllVelocityScores), ctx)
}

// CalculateVelocityScore mocks base method.
func (m *MockRankingService) CalculateVelocityScore(ctx context.Context, userID uuid.UUID) (*entity.UserVelocityScore, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CalculateVelocityScore", ctx, userID)
	ret0, _ := ret[0].(*entity.UserVelocityScore)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CalculateVelocityScore indicates an expected call of CalculateVelocityScore.
func (mr *MockRankingServiceMockRecorder) CalculateVelocityScore(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CalculateVelocityScore", reflect.TypeOf((*MockRankingService)(nil).CalculateVelocityScore), ctx, userID)
}

// GetUserRankingDetail mocks base method.
func (m *MockRankingService) GetUserRankingDetail(ctx context.Context, userID uuid.UUID) (*service.UserRankingDetail, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserRankingDetail", ctx, userID)
	ret0, _ := ret[0].(*service.UserRankingDetail)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserRankingDetail indicates an expected call of GetUserRankingDetail.
func (mr *MockRankingServiceMockRecorder) GetUserRankingDetail(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserRankingDetail", reflect.TypeOf((*MockRankingService)(nil).GetUserRankingDetail), ctx, userID)
}
