// Code generated by MockGen. DO NOT EDIT.
// Source: internal/domain/service/email_service.go
//
// Generated by this command:
//
//	mockgen -source=internal/domain/service/email_service.go -destination=internal/domain/service/mocks/mock_email_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/aiagent/internal/domain/entity"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockEmailService is a mock of EmailService interface.
type MockEmailService struct {
	ctrl     *gomock.Controller
	recorder *MockEmailServiceMockRecorder
	isgomock struct{}
}

// MockEmailServiceMockRecorder is the mock recorder for MockEmailService.
type MockEmailServiceMockRecorder struct {
	mock *MockEmailService
}

// NewMockEmailService creates a new mock instance.
func NewMockEmailService(ctrl *gomock.Controller) *MockEmailService {
	mock := &MockEmailService{ctrl: ctrl}
	mock.recorder = &MockEmailServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockEmailService) EXPECT() *MockEmailServiceMockRecorder {
	return m.recorder
}

// SendNotification mocks base method.
func (m *MockEmailService) SendNotification(ctx context.Context, userID uuid.UUID, notifType entity.NotificationType, data map[string]any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendNotification", ctx, userID, notifType, data)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendNotification indicates an expected call of SendNotification.
func (mr *MockEmailServiceMockRecorder) SendNotification(ctx, userID, notifType, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendNotification", reflect.TypeOf((*MockEmailService)(nil).SendNotification), ctx, userID, notifType, data)
}

// SendVerificationEmail mocks base method.
func (m *MockEmailService) SendVerificationEmail(ctx context.Context, userID uuid.UUID, email, token string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendVerificationEmail", ctx, userID, email, token)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendVerificationEmail indicates an expected call of SendVerificationEmail.
func (mr *MockEmailServiceMockRecorder) SendVerificationEmail(ctx, userID, email, token any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendVerificationEmail", reflect.TypeOf((*MockEmailService)(nil).SendVerificationEmail), ctx, userID, email, token)
}

// SendWelcomeEmail mocks base method.
func (m *MockEmailService) SendWelcomeEmail(ctx context.Context, userID uuid.UUID, email, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendWelcomeEmail", ctx, userID, email, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendWelcomeEmail indicates an expected call of SendWelcomeEmail.
func (mr *MockEmailServiceMockRecorder) SendWelcomeEmail(ctx, userID, email, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendWelcomeEmail", reflect.TypeOf((*MockEmailService)(nil).SendWelcomeEmail), ctx, userID, email, name)
}
