// Code generated by MockGen. DO NOT EDIT.
// Source: blog_service.go
//
// Generated by this command:
//
//	mockgen -source=blog_service.go -destination=mocks/mock_blog_service.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/aiagent/internal/domain/entity"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockBlogService is a mock of BlogService interface.
type MockBlogService struct {
	ctrl     *gomock.Controller
	recorder *MockBlogServiceMockRecorder
	isgomock struct{}
}

// MockBlogServiceMockRecorder is the mock recorder for MockBlogService.
type MockBlogServiceMockRecorder struct {
	mock *MockBlogService
}

// NewMockBlogService creates a new mock instance.
func NewMockBlogService(ctrl *gomock.Controller) *MockBlogService {
	mock := &MockBlogService{ctrl: ctrl}
	mock.recorder = &MockBlogServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBlogService) EXPECT() *MockBlogServiceMockRecorder {
	return m.recorder
}

// CheckAccess mocks base method.
func (m *MockBlogService) CheckAccess(ctx context.Context, blog *entity.Blog, viewerID *uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CheckAccess", ctx, blog, viewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// CheckAccess indicates an expected call of CheckAccess.
func (mr *MockBlogServiceMockRecorder) CheckAccess(ctx, blog, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CheckAccess", reflect.TypeOf((*MockBlogService)(nil).CheckAccess), ctx, blog, viewerID)
}

// Create mocks base method.
func (m *MockBlogService) Create(ctx context.Context, blog *entity.Blog, tagIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, blog, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockBlogServiceMockRecorder) Create(ctx, blog, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockBlogService)(nil).Create), ctx, blog, tagIDs)
}

// Delete mocks base method.
func (m *MockBlogService) Delete(ctx context.Context, id, authorID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, authorID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockBlogServiceMockRecorder) Delete(ctx, id, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockBlogService)(nil).Delete), ctx, id, authorID)
}

// GetByID mocks base method.
func (m *MockBlogService) GetByID(ctx context.Context, id uuid.UUID, viewerID *uuid.UUID) (*entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id, viewerID)
	ret0, _ := ret[0].(*entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockBlogServiceMockRecorder) GetByID(ctx, id, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockBlogService)(nil).GetByID), ctx, id, viewerID)
}

// GetBySlug mocks base method.
func (m *MockBlogService) GetBySlug(ctx context.Context, authorID uuid.UUID, slug string, viewerID *uuid.UUID) (*entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySlug", ctx, authorID, slug, viewerID)
	ret0, _ := ret[0].(*entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySlug indicates an expected call of GetBySlug.
func (mr *MockBlogServiceMockRecorder) GetBySlug(ctx, authorID, slug, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySlug", reflect.TypeOf((*MockBlogService)(nil).GetBySlug), ctx, authorID, slug, viewerID)
}

// List mocks base method.
func (m *MockBlogService) List(ctx context.Context, filter repository.BlogFilter, pagination repository.Pagination, viewerID *uuid.UUID) (*repository.PaginatedResult[entity.Blog], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, filter, pagination, viewerID)
	ret0, _ := ret[0].(*repository.PaginatedResult[entity.Blog])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockBlogServiceMockRecorder) List(ctx, filter, pagination, viewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockBlogService)(nil).List), ctx, filter, pagination, viewerID)
}

// Publish mocks base method.
func (m *MockBlogService) Publish(ctx context.Context, id, authorID uuid.UUID, visibility entity.BlogVisibility, publishedAt *time.Time) (*entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Publish", ctx, id, authorID, visibility, publishedAt)
	ret0, _ := ret[0].(*entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Publish indicates an expected call of Publish.
func (mr *MockBlogServiceMockRecorder) Publish(ctx, id, authorID, visibility, publishedAt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Publish", reflect.TypeOf((*MockBlogService)(nil).Publish), ctx, id, authorID, visibility, publishedAt)
}

// React mocks base method.
func (m *MockBlogService) React(ctx context.Context, id, userID uuid.UUID, reactionType entity.ReactionType) (int, int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "React", ctx, id, userID, reactionType)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(int)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// React indicates an expected call of React.
func (mr *MockBlogServiceMockRecorder) React(ctx, id, userID, reactionType any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "React", reflect.TypeOf((*MockBlogService)(nil).React), ctx, id, userID, reactionType)
}

// Unpublish mocks base method.
func (m *MockBlogService) Unpublish(ctx context.Context, id, authorID uuid.UUID) (*entity.Blog, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unpublish", ctx, id, authorID)
	ret0, _ := ret[0].(*entity.Blog)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unpublish indicates an expected call of Unpublish.
func (mr *MockBlogServiceMockRecorder) Unpublish(ctx, id, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unpublish", reflect.TypeOf((*MockBlogService)(nil).Unpublish), ctx, id, authorID)
}

// Update mocks base method.
func (m *MockBlogService) Update(ctx context.Context, blog *entity.Blog, tagIDs []uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, blog, tagIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockBlogServiceMockRecorder) Update(ctx, blog, tagIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockBlogService)(nil).Update), ctx, blog, tagIDs)
}
