// Code generated by MockGen. DO NOT EDIT.
// Source: internal/application/usecase/notification/usecase.go
//
// Generated by this command:
//
//	mockgen -source=internal/application/usecase/notification/usecase.go -destination=internal/application/usecase/notification/mocks/mock_usecase.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	dto "github.com/aiagent/internal/application/dto"
	repository "github.com/aiagent/internal/domain/repository"
	uuid "github.com/google/uuid"
	gomock "go.uber.org/mock/gomock"
)

// MockNotificationUseCase is a mock of NotificationUseCase interface.
type MockNotificationUseCase struct {
	ctrl     *gomock.Controller
	recorder *MockNotificationUseCaseMockRecorder
	isgomock struct{}
}

// MockNotificationUseCaseMockRecorder is the mock recorder for MockNotificationUseCase.
type MockNotificationUseCaseMockRecorder struct {
	mock *MockNotificationUseCase
}

// NewMockNotificationUseCase creates a new mock instance.
func NewMockNotificationUseCase(ctrl *gomock.Controller) *MockNotificationUseCase {
	mock := &MockNotificationUseCase{ctrl: ctrl}
	mock.recorder = &MockNotificationUseCaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNotificationUseCase) EXPECT() *MockNotificationUseCaseMockRecorder {
	return m.recorder
}

// GetPreferences mocks base method.
func (m *MockNotificationUseCase) GetPreferences(ctx context.Context, userID uuid.UUID) ([]dto.NotificationPreferenceResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPreferences", ctx, userID)
	ret0, _ := ret[0].([]dto.NotificationPreferenceResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPreferences indicates an expected call of GetPreferences.
func (mr *MockNotificationUseCaseMockRecorder) GetPreferences(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPreferences", reflect.TypeOf((*MockNotificationUseCase)(nil).GetPreferences), ctx, userID)
}

// GetUnreadCount mocks base method.
func (m *MockNotificationUseCase) GetUnreadCount(ctx context.Context, userID uuid.UUID) (int, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUnreadCount", ctx, userID)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUnreadCount indicates an expected call of GetUnreadCount.
func (mr *MockNotificationUseCaseMockRecorder) GetUnreadCount(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUnreadCount", reflect.TypeOf((*MockNotificationUseCase)(nil).GetUnreadCount), ctx, userID)
}

// List mocks base method.
func (m *MockNotificationUseCase) List(ctx context.Context, userID uuid.UUID, page, pageSize int) (*repository.PaginatedResult[dto.NotificationResponse], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, userID, page, pageSize)
	ret0, _ := ret[0].(*repository.PaginatedResult[dto.NotificationResponse])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockNotificationUseCaseMockRecorder) List(ctx, userID, page, pageSize any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockNotificationUseCase)(nil).List), ctx, userID, page, pageSize)
}

// MarkAllAsRead mocks base method.
func (m *MockNotificationUseCase) MarkAllAsRead(ctx context.Context, userID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAllAsRead", ctx, userID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAllAsRead indicates an expected call of MarkAllAsRead.
func (mr *MockNotificationUseCaseMockRecorder) MarkAllAsRead(ctx, userID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAllAsRead", reflect.TypeOf((*MockNotificationUseCase)(nil).MarkAllAsRead), ctx, userID)
}

// MarkAsRead mocks base method.
func (m *MockNotificationUseCase) MarkAsRead(ctx context.Context, userID, notificationID uuid.UUID) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkAsRead", ctx, userID, notificationID)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkAsRead indicates an expected call of MarkAsRead.
func (mr *MockNotificationUseCaseMockRecorder) MarkAsRead(ctx, userID, notificationID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkAsRead", reflect.TypeOf((*MockNotificationUseCase)(nil).MarkAsRead), ctx, userID, notificationID)
}

// RegisterDeviceToken mocks base method.
func (m *MockNotificationUseCase) RegisterDeviceToken(ctx context.Context, userID uuid.UUID, req dto.RegisterDeviceTokenRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RegisterDeviceToken", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// RegisterDeviceToken indicates an expected call of RegisterDeviceToken.
func (mr *MockNotificationUseCaseMockRecorder) RegisterDeviceToken(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterDeviceToken", reflect.TypeOf((*MockNotificationUseCase)(nil).RegisterDeviceToken), ctx, userID, req)
}

// UpdatePreferences mocks base method.
func (m *MockNotificationUseCase) UpdatePreferences(ctx context.Context, userID uuid.UUID, req dto.UpdatePreferencesRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdatePreferences", ctx, userID, req)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdatePreferences indicates an expected call of UpdatePreferences.
func (mr *MockNotificationUseCaseMockRecorder) UpdatePreferences(ctx, userID, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdatePreferences", reflect.TypeOf((*MockNotificationUseCase)(nil).UpdatePreferences), ctx, userID, req)
}
